// Cross-check: every pass id used in any shipped YAML profile must
// be registered in the Container's enrichment runner.
//
// We can't import the Python registry from TS, so the Container ships
// a generated JSON manifest at apps/ingest/app/enrichment/_registry.json
// (generated by `python apps/ingest/scripts/dump_registry.py`). A CI
// step ensures the manifest matches the live Python registry.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { listProfiles } from '../src/loader.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRY_PATH = join(
  __dirname,
  '..',
  '..',
  '..',
  'apps',
  'ingest',
  'app',
  'enrichment',
  '_registry.json',
);

describe('enrichment registry coverage', () => {
  it('every pass id in every shipped profile is registered in the Container', () => {
    const registered = new Set<string>(JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')));
    for (const profile of listProfiles()) {
      for (const pass of profile.enrichment.passes) {
        expect(
          registered.has(pass.id),
          `profile ${profile.id}: pass ${pass.id} not in Container registry`,
        ).toBe(true);
      }
    }
  });
});
