// Compiles ../profiles/*.yaml → ../src/_generated.ts.
//
// Run via `pnpm --filter @textral/corpus-profiles gen`. Re-run any
// time a YAML changes; the generated file is committed so the Worker
// (which can't readdirSync at runtime) always has its profiles.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROFILES_DIR = join(__dirname, '..', 'profiles');
const OUT = join(__dirname, '..', 'src', '_generated.ts');

const entries: Array<[string, unknown]> = [];
for (const file of readdirSync(PROFILES_DIR).sort()) {
  if (!file.endsWith('.yaml') && !file.endsWith('.yml')) continue;
  const raw = parseYaml(readFileSync(join(PROFILES_DIR, file), 'utf8')) as Record<string, unknown>;
  const id = raw['id'];
  if (typeof id !== 'string' || id.length === 0) {
    throw new Error(`${file} missing string id`);
  }
  entries.push([id, raw]);
}

const ids = entries.map(([id]) => id).sort();
if (!ids.includes('generic')) {
  throw new Error('generic profile missing');
}

const body = `// AUTO-GENERATED by scripts/gen.ts. Do not edit.
// Regenerate with: pnpm --filter @textral/corpus-profiles gen

export const GENERATED_PROFILES = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  2,
)} as const;
`;
writeFileSync(OUT, body, 'utf8');
console.log(`Wrote ${OUT} with ${entries.length} profiles: ${ids.join(', ')}`);
