"""Regenerate src/textral/models/ from
@textral/contracts/dist/schemas/*.json.

Usage:
    python codegen/generate.py [--check]

`--check` exits non-zero if regeneration would change any file
(used by CI to catch contract drift that didn't refresh the
generated models).

The pipeline:

    @textral/contracts/dist/schemas/*.json
        ↓ datamodel-code-generator
    src/textral/models/*.py     ← AUTO-GENERATED, do not edit
        ↓ post-process
    + write src/textral/models/__init__.py barrel
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
CONTRACTS_SCHEMAS = ROOT.parent / "contracts" / "dist" / "schemas"
LOCAL_SCHEMAS = ROOT / "codegen" / "schemas"
OUTPUT_DIR = ROOT / "src" / "textral" / "models"


def stage_schemas() -> None:
    """Copy schemas from @textral/contracts into a local staging
    dir. Done as a deliberate step so codegen runs against a stable
    snapshot — and so the diff fingerprint includes the schemas
    themselves, not just the generated Python."""
    LOCAL_SCHEMAS.mkdir(parents=True, exist_ok=True)
    for f in LOCAL_SCHEMAS.glob("*.json"):
        f.unlink()
    if not CONTRACTS_SCHEMAS.exists():
        sys.exit(
            f"contracts schemas not found at {CONTRACTS_SCHEMAS}.\n"
            f"Run `pnpm --filter @textral/contracts build` first."
        )
    for f in CONTRACTS_SCHEMAS.glob("*.json"):
        shutil.copy(f, LOCAL_SCHEMAS / f.name)


def generate() -> None:
    """Run datamodel-code-generator over every schema in the
    staging dir; emit one Python module per schema into
    src/textral/models/."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe everything except __init__.py (the hand-maintained
    # barrel) — but we'll regenerate that too at the end.
    for f in OUTPUT_DIR.glob("*.py"):
        f.unlink()

    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(LOCAL_SCHEMAS),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(OUTPUT_DIR),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.10",
        "--use-double-quotes",
        "--use-annotated",
        "--field-constraints",
        "--use-schema-description",
        "--use-field-description",
        "--use-default",
        "--snake-case-field",
        "--collapse-root-models",
        "--reuse-model",
        "--enum-field-as-literal",
        "all",
    ]
    subprocess.run(cmd, check=True)


def post_process() -> None:
    """Two cleanups on top of datamodel-code-generator's output:

    1. Rename `class Model(...)` → `class {filename}(...)` when the
       filename's class doesn't already exist. This handles
       top-level enums and root-models cleanly. For object files
       where both `class {filename}` and `class Model(RootModel[
       {filename}])` already exist, drop the redundant `Model`
       wrapper (it's a tautological alias).

    2. Replace `extra="forbid"` → `extra="allow"` so server-side
       additive changes don't break the Python client. Pydantic
       still validates declared fields strictly.
    """
    for py in OUTPUT_DIR.glob("*.py"):
        if py.name == "__init__.py":
            continue
        text = py.read_text()
        stem = py.stem

        has_named_class = re.search(rf"^class {re.escape(stem)}\b", text, re.MULTILINE)
        if has_named_class:
            # Drop the tautological Model alias at end of file.
            text = re.sub(
                rf"\n*class Model\(RootModel\[{re.escape(stem)}\]\):\n    root: {re.escape(stem)}\s*\n*$",
                "\n",
                text,
            )
        else:
            # Rename Model → stem.
            text = re.sub(
                r"^class Model\b",
                f"class {stem}",
                text,
                count=1,
                flags=re.MULTILINE,
            )

        text = text.replace('extra="forbid"', 'extra="allow"')
        py.write_text(text)


def write_init() -> None:
    """Generate src/textral/models/__init__.py — re-exports the
    top-level class from each generated module so callers can
    write `from textral.models import BulkSubmitRequest`.

    Important: only the file-stem class is re-exported, never the
    nested inner classes. Inner classes (`class Embedding` inside
    `BulkSubmitRequest.py`, etc.) collide across files and would
    cause mypy + IDE confusion. Callers can still reach them via
    `BulkSubmitRequest.Embedding`."""
    class_pattern = re.compile(r"^class (\w+)\b", re.MULTILINE)
    barrel_lines: list[str] = [
        "# AUTO-GENERATED by codegen/generate.py — do not edit by hand.",
        "# Re-exports the top-level Pydantic model from each submodule.",
        "# Nested classes are accessed as BulkSubmitRequest.Embedding etc.",
        "",
    ]
    public: list[str] = []
    for py in sorted(OUTPUT_DIR.glob("*.py")):
        if py.name == "__init__.py":
            continue
        module_name = py.stem
        text = py.read_text()
        classes = class_pattern.findall(text)
        # The file-stem class is the public top-level model. Skip
        # the file if no class matches the stem.
        if module_name not in classes:
            continue
        barrel_lines.append(f"from .{module_name} import {module_name}")
        public.append(module_name)

    barrel_lines.append("")
    barrel_lines.append("__all__ = [")
    for c in sorted(set(public)):
        barrel_lines.append(f'    "{c}",')
    barrel_lines.append("]")
    barrel_lines.append("")

    (OUTPUT_DIR / "__init__.py").write_text("\n".join(barrel_lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if regeneration would change any file (CI mode).",
    )
    args = parser.parse_args()

    stage_schemas()
    generate()
    post_process()
    write_init()

    if args.check:
        # Ask git whether anything in OUTPUT_DIR or LOCAL_SCHEMAS
        # changed. Run from the repo root so the .git lookup works.
        repo_root = ROOT.parent.parent
        result = subprocess.run(
            [
                "git",
                "diff",
                "--exit-code",
                "--",
                str(OUTPUT_DIR.relative_to(repo_root)),
                str(LOCAL_SCHEMAS.relative_to(repo_root)),
            ],
            cwd=repo_root,
        )
        if result.returncode != 0:
            sys.stderr.write(
                "\n"
                "Generated Pydantic models drifted from the contracts schemas.\n"
                "Run `python codegen/generate.py` (no --check) and commit.\n"
            )
            sys.exit(1)


if __name__ == "__main__":
    main()
