// Hand-crafted code samples for the flagship endpoints.
//
// Per docs/SCALAR_DOCS_ENHANCEMENT_PLAN.md §10 +
// docs/development/sdks/SDK_PUBLIC_DOCUMENTATION.md. Each entry is keyed
// by (method, path); applyCodeSamples() walks the generated OpenAPI doc
// and attaches `x-codeSamples` to the matching operation. operationIds
// are auto-generated by @hono/zod-openapi, so keying by (method, path)
// is the durable contract.
//
// Languages:
//   * shell  — curl, the "no-deps" tab
//   * js     — Node SDK (@textral/sdk)
//   * python — Python SDK (textral)
//
// Curl samples use placeholder strings the user replaces:
//   {{TENANT_API_KEY}}  → their own X-Textral-Api-Key
//   {{WORKER_URL}}      → e.g. https://textral-api-dev.<sub>.workers.dev
//
// SDK samples use **profile mode** — the canonical credential path,
// `~/.textral/profiles.toml`. Explicit `baseUrl` / `apiKey` is shown
// in the SDK pages; samples pick one path and stick with it so each
// snippet is paste-and-run with no editing.

export interface CodeSample {
  lang: 'shell' | 'js' | 'python';
  label: string;
  source: string;
}

export interface SampleKey {
  method: 'get' | 'post' | 'put' | 'delete' | 'patch';
  path: string;
}

interface SampleEntry {
  key: SampleKey;
  samples: CodeSample[];
}

const KEY = '{{TENANT_API_KEY}}';
const URL_ = '{{WORKER_URL}}';

// ── SDK sample builders ─────────────────────────────────────────────
//
// Each entry's js/python sample is one client construction +
// one call. The helpers fold the imports + boilerplate into
// per-entry one-liners so the file stays reviewable as new
// endpoints land.

function nodeSdk(callBody: string, label = 'Node (@textral/sdk)'): CodeSample {
  return {
    lang: 'js',
    label,
    source: `import { TextralClient } from '@textral/sdk';

const client = new TextralClient({ profile: 'hosted-prod' });

${callBody}`,
  };
}

function pythonSdk(callBody: string, label = 'Python (textral)'): CodeSample {
  return {
    lang: 'python',
    label,
    source: `from textral import Client

with Client(profile="hosted-prod") as client:
${callBody}`,
  };
}

// ─── 1. Auth sanity check ──────────────────────────────────────────
const ME: SampleEntry = {
  key: { method: 'get', path: '/v1/me' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -s "${URL_}/v1/me" \\
  -H "X-Textral-Api-Key: ${KEY}"`,
    },
    nodeSdk(`const me = await client.me();
console.log(me.tenant_id);`),
    pythonSdk(`    me = client.me()
    print(me["tenant_id"])`),
  ],
};

// ─── 2. Register a provider key (BYOK) ─────────────────────────────
const REG_PROVIDER_KEY: SampleEntry = {
  key: { method: 'post', path: '/v1/provider-keys' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/provider-keys" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "provider": "openai",
    "label": "default",
    "key": "sk-..."
  }'`,
    },
    nodeSdk(`const { id } = await client.providerKeys.create({
  provider: 'openai',
  label: 'default',
  key: process.env.OPENAI_API_KEY!,
});
console.log(id); // pkey_…`),
    pythonSdk(`    import os
    r = client.provider_keys.create({
        "provider": "openai",
        "label": "default",
        "key": os.environ["OPENAI_API_KEY"],
    })
    print(r["id"])  # pkey_...`),
  ],
};

// ─── 3. Create a namespace ────────────────────────────────────────
const REG_NAMESPACE: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "generic",
    "default_embedding_profile": "openai-text-embedding-3-large-1536"
  }'

# corpus_profile options: generic | narrative | legal | support | technical`,
    },
    nodeSdk(`const ns = await client.namespaces.create({
  slug: 'my-docs',
  corpus_profile: 'generic',
  default_embedding_profile: 'openai-text-embedding-3-large-1536',
});
console.log(ns.id); // ns_…`),
    pythonSdk(`    ns = client.namespaces.create({
        "slug": "my-docs",
        "corpus_profile": "generic",
        "default_embedding_profile": "openai-text-embedding-3-large-1536",
    })
    print(ns["id"])`),
    // ── V3 Phase 1 — alternate vector backend variants. ──
    {
      lang: 'shell',
      label: 'curl (Qdrant backend)',
      source: `curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "narrative",
    "default_embedding_profile": "openai-text-embedding-3-large-1536",
    "vector_backend": "qdrant",
    "vector_index_name": "my-docs-passages"
  }'

# Adapter auto-creates the Qdrant collection with size=dimensions and
# cosine distance. Operator must set QDRANT_URL on the deploy.`,
    },
    {
      lang: 'shell',
      label: 'curl (Pinecone backend)',
      source: `# 1) Pre-provision a serverless index in the Pinecone console
#    (dimensions=1536, cosine). Copy the host URL it shows.
# 2) Set PINECONE_API_KEY on the deploy via wrangler secret put.
# 3) Create the namespace pointing at the host:
curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "narrative",
    "default_embedding_profile": "openai-text-embedding-3-large-1536",
    "vector_backend": "pinecone",
    "vector_index_name": "https://my-idx-xxxxx.svc.us-east-1-aws.pinecone.io"
  }'`,
    },
  ],
};

// ─── 4. Register a document ───────────────────────────────────────
const REG_DOCUMENT: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces/{slug}/documents' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/documents" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "title": "API Reference",
    "doc_type": "technical"
  }'`,
    },
    nodeSdk(`const doc = await client.documents.register('my-docs', {
  title: 'API Reference',
  doc_type: 'technical',
});
console.log(doc.id); // doc_…`),
    pythonSdk(`    doc = client.documents.register(
        "my-docs",
        title="API Reference",
        doc_type="technical",
    )
    print(doc["id"])`),
  ],
};

// ─── 5. Upload bytes (presign + PUT, two-step) ────────────────────
const UPLOAD_BYTES: SampleEntry = {
  key: { method: 'post', path: '/v1/documents/{id}/uploads' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Step 1: get the upload URL.
UPLOAD_JSON=$(curl -s -X POST "${URL_}/v1/documents/$DOC_ID/uploads" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "content_type": "text/markdown",
    "size_bytes": '"$(stat -c%s ./mydoc.md)"'
  }')

UPLOAD_URL=$(echo "$UPLOAD_JSON" | jq -r .url)
UPLOAD_ID=$(echo "$UPLOAD_JSON" | jq -r .upload_id)

# Step 2: PUT the bytes (URL points back at the Worker — proxied).
curl -X PUT "$UPLOAD_URL" \\
  -H 'content-type: text/markdown' \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  --data-binary @./mydoc.md

# Step 3: see the finalize sample.`,
    },
    nodeSdk(`import { readFileSync, statSync } from 'node:fs';

const bytes = readFileSync('./mydoc.md');
const upload = await client.documents.createUpload(docId, {
  content_type: 'text/markdown',
  size_bytes: statSync('./mydoc.md').size,
});
await client.documents.putUploadBytes(upload.url, bytes, 'text/markdown');
// Then call client.documents.finalize(docId, upload.upload_id).`),
    pythonSdk(`    from pathlib import Path

    bytes_ = Path("./mydoc.md").read_bytes()
    upload = client.documents.create_upload(
        doc_id,
        content_type="text/markdown",
        size_bytes=len(bytes_),
    )
    client.documents.put_upload_bytes(upload["url"], bytes_, "text/markdown")
    # Then call client.documents.finalize(doc_id, upload["upload_id"]).`),
  ],
};

// ─── 6. Finalize upload ───────────────────────────────────────────
const FINALIZE_UPLOAD: SampleEntry = {
  key: {
    method: 'post',
    path: '/v1/documents/{id}/uploads/{upload_id}/finalize',
  },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/documents/$DOC_ID/uploads/$UPLOAD_ID/finalize" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{}'

# Returns version_id; pass it to /ingest.`,
    },
    nodeSdk(`const fin = await client.documents.finalize(docId, uploadId);
console.log(fin.version_id); // v_…`),
    pythonSdk(`    fin = client.documents.finalize(doc_id, upload_id)
    print(fin["version_id"])`),
  ],
};

// ─── 7. Trigger ingestion ─────────────────────────────────────────
const INGEST: SampleEntry = {
  key: { method: 'post', path: '/v1/documents/{id}/ingest' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Minimal RAG path: generic profile, default chunking, mode=full.
curl -X POST "${URL_}/v1/documents/$DOC_ID/ingest" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "version_id": "'"$VERSION_ID"'",
    "embedding": {
      "provider": "openai",
      "model": "text-embedding-3-large",
      "dimensions": 1536,
      "provider_key_ref": "default"
    },
    "chunking": { "profile": "generic" },
    "mode": "full"
  }'

# Returns job_id; poll GET /v1/ingestion-jobs/{id} until status=completed.`,
    },
    nodeSdk(`const job = await client.documents.ingest(docId, {
  version_id: versionId,
  embedding: {
    provider: 'openai',
    model: 'text-embedding-3-large',
    dimensions: 1536,
    provider_key_ref: 'default',
  },
  chunking: { profile: 'generic' },
  mode: 'full',
});
console.log(job.job_id);`),
    pythonSdk(`    job = client.documents.ingest(doc_id, {
        "version_id": version_id,
        "embedding": {
            "provider": "openai",
            "model": "text-embedding-3-large",
            "dimensions": 1536,
            "provider_key_ref": "default",
        },
        "chunking": {"profile": "generic"},
        "mode": "full",
    })
    print(job["job_id"])`),
  ],
};

// ─── 8. Poll an ingestion job ─────────────────────────────────────
const POLL_JOB: SampleEntry = {
  key: { method: 'get', path: '/v1/ingestion-jobs/{id}' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Polling loop (simplified).
while true; do
  STATUS=$(curl -s "${URL_}/v1/ingestion-jobs/$JOB_ID" \\
    -H "X-Textral-Api-Key: ${KEY}" | jq -r .status)
  echo "status: $STATUS"
  case "$STATUS" in
    completed|failed) break ;;
    *) sleep 5 ;;
  esac
done`,
    },
    nodeSdk(`async function pollJob(jobId: string, timeoutMs = 240_000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const j = await client.ingestionJobs.get(jobId);
    if (j.status === 'completed' || j.status === 'failed') return j;
    await new Promise((r) => setTimeout(r, 5_000));
  }
  throw new Error('job poll timed out');
}`),
    pythonSdk(`    import time

    def poll_job(job_id: str, timeout_s: int = 240):
        start = time.time()
        while time.time() - start < timeout_s:
            j = client.ingestion_jobs.get(job_id)
            if j["status"] in ("completed", "failed"):
                return j
            time.sleep(5)
        raise TimeoutError("job poll timed out")`),
  ],
};

// ─── 9. Sync query ────────────────────────────────────────────────
const SYNC_QUERY: SampleEntry = {
  key: { method: 'post', path: '/v1/query' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Minimal query body — generic profile, hybrid retrieval.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does the doc say about X?",
    "embedding": {
      "provider": "openai",
      "model": "text-embedding-3-large",
      "dimensions": 1536,
      "provider_key_ref": "default"
    },
    "inference": {
      "provider": "openai",
      "model": "gpt-4o-mini",
      "provider_key_ref": "default"
    },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 }
  }'

# Append ?stream=sse for Server-Sent Events streaming.`,
    },
    nodeSdk(`const r = await client.query({
  namespace: 'my-docs',
  query: 'What does the doc say about X?',
  embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
  inference:  { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
  chunking:   { profile: 'generic' },
  retrieval:  { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
});
console.log(r.answer.text, r.citations, r.audit.degradation_level);`),
    pythonSdk(`    r = client.query(
        namespace="my-docs",
        query="What does the doc say about X?",
        embedding={"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        inference={"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        chunking={"profile": "generic"},
        retrieval={"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
    )
    print(r["answer"]["text"], r["citations"], r["audit"]["degradation_level"])`),
  ],
};

// ─── 10. Streaming query (SSE) ────────────────────────────────────
// Same path as #9 but with ?stream=sse — Scalar shows it as a
// separate operation only if we register it as one. For now we
// document it inside the sync query's description and as a
// snippet here keyed on the same path; the renderer dedupes by
// (path, method) so we attach this as an *additional* sample on
// the sync query.
const STREAMING_QUERY_SAMPLE: CodeSample[] = [
  {
    lang: 'shell',
    label: 'curl (?stream=sse)',
    source: `curl -N -X POST "${URL_}/v1/query?stream=sse" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'accept: text/event-stream' \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does the doc say about X?",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 }
  }'

# Two event types: token (per delta) and done (single final event).`,
  },
  {
    lang: 'js',
    label: 'Node SDK — streaming',
    source: `import { TextralClient } from '@textral/sdk';

const client = new TextralClient({ profile: 'hosted-prod' });

for await (const frame of client.query.stream({
  namespace: 'my-docs',
  query: 'What does the doc say about X?',
  embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
  inference:  { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
  chunking:   { profile: 'generic' },
  retrieval:  { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
})) {
  if (frame.type === 'token') process.stdout.write(frame.value);
  else if (frame.type === 'done') console.log('\\n', frame.degradation_level);
}`,
  },
  {
    lang: 'python',
    label: 'Python SDK — streaming (async)',
    source: `import asyncio
from textral import AsyncClient

async def main():
    async with AsyncClient(profile="hosted-prod") as client:
        async for frame in client.query.stream(
            namespace="my-docs",
            query="What does the doc say about X?",
            embedding={"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
            inference={"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
            chunking={"profile": "generic"},
            retrieval={"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
        ):
            if frame.get("event") == "answer_token":
                print(frame.get("value", ""), end="", flush=True)
            elif frame.get("event") == "final":
                print()
                print(f"degradation: {frame.get('degradation_level')}")

asyncio.run(main())`,
  },
];

// ─── Cookbook patterns (attached as additional samples on POST /v1/query) ──

const COOKBOOK_STRUCTURED_SIMPLE: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 2: structured (simple)',
    source: `# Constrain output to a JSON schema. answer.object comes back parsed.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Name two scholars connected to Alexandria.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "output": {
      "mode": "structured",
      "schema": {
        "type": "object",
        "properties": {
          "scholars": { "type": "array", "items": { "type": "string" } }
        },
        "required": ["scholars"],
        "additionalProperties": false
      }
    }
  }'
# Response: answer.mode = "structured", answer.object = { "scholars": [...] }
# Note: omitting a "citations" field in the schema means top-level citations[] will be empty.`,
  },
  nodeSdk(
    `const r = await client.query({
  namespace: 'my-docs',
  query: 'Name two scholars connected to Alexandria.',
  embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
  inference:  { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
  chunking:   { profile: 'generic' },
  retrieval:  { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
  output: {
    mode: 'structured',
    schema: {
      type: 'object',
      properties: { scholars: { type: 'array', items: { type: 'string' } } },
      required: ['scholars'],
      additionalProperties: false,
    },
  },
});
if (r.answer.mode === 'structured') {
  const obj = r.answer.object as { scholars: string[] };
  console.log(obj.scholars);
}`,
    'Pattern 2: structured (simple)',
  ),
  pythonSdk(
    `    r = client.query(
        namespace="my-docs",
        query="Name two scholars connected to Alexandria.",
        embedding={"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        inference={"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        chunking={"profile": "generic"},
        retrieval={"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
        output={
            "mode": "structured",
            "schema": {
                "type": "object",
                "properties": {"scholars": {"type": "array", "items": {"type": "string"}}},
                "required": ["scholars"],
                "additionalProperties": False,
            },
        },
    )
    print(r["answer"]["object"]["scholars"])`,
    'Pattern 2: structured (simple)',
  ),
];

const COOKBOOK_STRUCTURED_NESTED: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 3: structured (nested + citations)',
    source: `# Schema with a top-level citations[] field round-trips:
# the platform filters citations to retrieved chunks and
# also resolves them into the response's top-level citations[].
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "List the scholars mentioned and what each is known for.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "output": {
      "mode": "structured",
      "schema": {
        "type": "object",
        "properties": {
          "scholars": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": { "name": { "type": "string" }, "known_for": { "type": "string" } },
              "required": ["name", "known_for"],
              "additionalProperties": false
            }
          },
          "citations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": { "chunk_id": { "type": "string" }, "quote": { "type": "string" } },
              "required": ["chunk_id", "quote"],
              "additionalProperties": false
            }
          }
        },
        "required": ["scholars", "citations"],
        "additionalProperties": false
      }
    }
  }'
# Gotcha: OpenAI strict mode requires every property in 'required'.
# If "quote" were optional here, synthesis would fail with
# degradation_level=cannot_answer.`,
  },
  nodeSdk(
    `const schema = {
  type: 'object',
  properties: {
    scholars: {
      type: 'array',
      items: {
        type: 'object',
        properties: { name: { type: 'string' }, known_for: { type: 'string' } },
        required: ['name', 'known_for'],
        additionalProperties: false,
      },
    },
    citations: {
      type: 'array',
      items: {
        type: 'object',
        properties: { chunk_id: { type: 'string' }, quote: { type: 'string' } },
        required: ['chunk_id', 'quote'],   // strict mode requires both
        additionalProperties: false,
      },
    },
  },
  required: ['scholars', 'citations'],
  additionalProperties: false,
};

const r = await client.query({
  namespace: 'my-docs',
  query: 'List the scholars mentioned and what each is known for.',
  embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
  inference:  { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
  chunking:   { profile: 'generic' },
  retrieval:  { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
  output:     { mode: 'structured', schema },
});
console.log(r.answer.object.scholars);
console.log('top-level citations:', r.citations);`,
    'Pattern 3: structured (nested + citations)',
  ),
  pythonSdk(
    `    schema = {
        "type": "object",
        "properties": {
            "scholars": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {"name": {"type": "string"}, "known_for": {"type": "string"}},
                    "required": ["name", "known_for"],
                    "additionalProperties": False,
                },
            },
            "citations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {"chunk_id": {"type": "string"}, "quote": {"type": "string"}},
                    "required": ["chunk_id", "quote"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["scholars", "citations"],
        "additionalProperties": False,
    }
    r = client.query(
        namespace="my-docs",
        query="List the scholars mentioned and what each is known for.",
        embedding={"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        inference={"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        chunking={"profile": "generic"},
        retrieval={"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
        output={"mode": "structured", "schema": schema},
    )
    print(r["answer"]["object"]["scholars"])
    print("top-level citations:", r["citations"])`,
    'Pattern 3: structured (nested + citations)',
  ),
];

const COOKBOOK_DOC_SUBSET: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 5: document subset',
    source: `# Scope retrieval to specific documents within the namespace.
# Useful when a tenant has many docs but the query is about a known few.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does this contract say about termination?",
    "document_ids": ["doc_01HABC...", "doc_01HDEF..."],
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 10, "top_k_sparse": 10 }
  }'`,
  },
];

const COOKBOOK_CUSTOM_PROMPT: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 6: custom system prompt',
    source: `# Override the corpus profile's default system prompt.
# The platform appends a mandatory citation suffix to your prompt;
# you cannot opt out of citation grounding.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Who was Eratosthenes?",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "prompt": {
      "system": "You are a careful research assistant. Reply in two sentences max."
    }
  }'`,
  },
];

const COOKBOOK_FAILURE_RECOVERY: CodeSample[] = [
  nodeSdk(
    `// Branch on degradation_level + audit fields to handle each
// failure mode distinctly. Reuses the same client from above.
const r = await client.query({ /* ... */ });

switch (r.degradation_level) {
  case 'full':
    return r.answer;
  case 'partial':
    return { ...r.answer, warning: 'some citations were dropped' };
  case 'no_citations':
    if (!r.audit.reranker.executed) return retryWithStrongerModel();
    return { ...r.answer, warning: 'answer not citation-grounded' };
  case 'cannot_answer':
    console.error('cannot_answer; query_event:', r.query_event_id);
    return { error: 'answer unavailable' };
}`,
    'Pattern 7: cannot-answer recovery',
  ),
  pythonSdk(
    `    r = client.query(...)
    deg = r["degradation_level"]

    if deg == "full":
        return r["answer"]
    elif deg == "partial":
        return {**r["answer"], "warning": "some citations were dropped"}
    elif deg == "no_citations":
        if not r["audit"]["reranker"]["executed"]:
            return retry_with_stronger_model()
        return {**r["answer"], "warning": "answer not citation-grounded"}
    elif deg == "cannot_answer":
        print(f"cannot_answer; query_event: {r['query_event_id']}")
        return {"error": "answer unavailable"}`,
    'Pattern 7: cannot-answer recovery',
  ),
];

const COOKBOOK_TOKEN_BUDGET: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 8: token budget tweak',
    source: `# Tighten context.max_context_tokens for cheap models or
# latency-sensitive paths. Default is 12000.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Summarise the corpus in two sentences.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "context": { "max_context_tokens": 1500 }
  }'`,
  },
];

// ─── 11. Bulk ingest (orchestrator) ───────────────────────────────
// New entry — the SDKs each ship a `bulkIngestOrchestrate` /
// `bulk_ingest_orchestrate` helper that drives the manifest →
// parallel uploads → optional finalize → poll dance in one call.
// Curl needs the manual three-step dance; SDK samples use the helper.
const BULK_INGEST: SampleEntry = {
  key: { method: 'post', path: '/v1/ingest/bulk' },
  samples: [
    {
      lang: 'shell',
      label: 'curl (manual three-step)',
      source: `# 1) Submit manifest. Server returns one upload URL per file.
SUBMIT_JSON=$(curl -s -X POST "${URL_}/v1/ingest/bulk" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "config": {
      "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
      "chunking":  { "profile": "generic" },
      "mode": "full"
    },
    "files": [
      { "ordinal": 0, "filename": "a.md", "size_bytes": 1234, "content_type": "text/markdown" },
      { "ordinal": 1, "filename": "b.md", "size_bytes": 5678, "content_type": "text/markdown" }
    ],
    "on_existing": "skip_if_unchanged",
    "auto_finalize": true
  }')

BULK_JOB_ID=$(echo "$SUBMIT_JSON" | jq -r .bulk_job_id)

# 2) PUT each file's bytes to its server-minted upload_url (parallel).
echo "$SUBMIT_JSON" | jq -c .uploads[] | while read SLOT; do
  ORDINAL=$(echo "$SLOT" | jq -r .ordinal)
  URL=$(echo "$SLOT" | jq -r .upload_url)
  case "$ORDINAL" in
    0) FILE=./a.md ;;
    1) FILE=./b.md ;;
  esac
  curl -X PUT "$URL" -H 'content-type: text/markdown' --data-binary @"$FILE" &
done
wait

# 3) (auto_finalize: true above) Poll until terminal.
while true; do
  STATE=$(curl -s "${URL_}/v1/ingest/bulk/$BULK_JOB_ID" \\
    -H "X-Textral-Api-Key: ${KEY}" | jq -r .state)
  echo "state: $STATE"
  case "$STATE" in
    complete|partial|failed|cancelled|expired) break ;;
    *) sleep 2 ;;
  esac
done`,
    },
    {
      lang: 'js',
      label: 'Node SDK — bulkIngestOrchestrate',
      source: `import { TextralClient, bulkIngestOrchestrate } from '@textral/sdk';
import { readFileSync, statSync } from 'node:fs';

const client = new TextralClient({ profile: 'hosted-prod' });

const result = await bulkIngestOrchestrate(client, {
  namespace: 'my-docs',
  config: {
    embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
    chunking:  { profile: 'generic' },
    mode: 'full',
  },
  files: ['a.md', 'b.md'].map((name) => ({
    filename: name,
    bytes: readFileSync(name),
    size_bytes: statSync(name).size,
    content_type: 'text/markdown',
  })),
  on_existing: 'skip_if_unchanged',
  auto_finalize: true,
  concurrency: 4,
  onProgress: (snap) => console.log(snap.state, snap.progress_pct + '%'),
});
console.log(result.bulk_job_id, result.final_status.state);`,
    },
    {
      lang: 'python',
      label: 'Python SDK — bulk_ingest_orchestrate',
      source: `from pathlib import Path
from textral import Client, BulkOrchestrateFile, bulk_ingest_orchestrate

with Client(profile="hosted-prod") as client:
    result = bulk_ingest_orchestrate(
        client,
        namespace="my-docs",
        config={
            "embedding": {"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
            "chunking":  {"profile": "generic"},
            "mode": "full",
        },
        files=[
            BulkOrchestrateFile(
                filename=name,
                bytes_=Path(name).read_bytes(),
                size_bytes=Path(name).stat().st_size,
                content_type="text/markdown",
            )
            for name in ("a.md", "b.md")
        ],
        on_existing="skip_if_unchanged",
        auto_finalize=True,
        concurrency=4,
        on_progress=lambda snap: print(snap.get("state"), f"{snap.get('progress_pct', 0)}%"),
    )

print(result.bulk_job_id, result.final_status["state"])`,
    },
  ],
};

// ─── 12. Register an eval set ─────────────────────────────────────
const REG_EVAL_SET: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces/{slug}/eval-sets' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/eval-sets" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "name": "baseline-v1",
    "questions": [
      { "question": "What does the doc say about X?",
        "expected_answer": "It says foo." },
      { "question": "Who wrote it?" }
    ]
  }'`,
    },
    nodeSdk(`// Eval set creation isn't on a typed resource yet; use the
// underlying request helper. Sister method is on the roadmap.
const set = await client._request({
  method: 'POST',
  path: '/v1/namespaces/my-docs/eval-sets',
  body: {
    name: 'baseline-v1',
    questions: [
      { question: 'What does the doc say about X?', expected_answer: 'It says foo.' },
      { question: 'Who wrote it?' },
    ],
  },
});
console.log(set.id);`),
    pythonSdk(`    # Eval set creation isn't on a typed resource yet; use the
    # underlying _http helper. Sister method is on the roadmap.
    set_ = client._http.request(
        "POST",
        "/v1/namespaces/my-docs/eval-sets",
        json={
            "name": "baseline-v1",
            "questions": [
                {"question": "What does the doc say about X?", "expected_answer": "It says foo."},
                {"question": "Who wrote it?"},
            ],
        },
    )
    print(set_["id"])`),
  ],
};

// ─── 13. Kick off an eval run ─────────────────────────────────────
const RUN_EVAL: SampleEntry = {
  key: {
    method: 'post',
    path: '/v1/namespaces/{slug}/eval-sets/{id}/runs',
  },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/eval-sets/$SET_ID/runs" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "pass_threshold": 4
  }'

# Synchronous: returns once every question completes.`,
    },
    nodeSdk(`// Eval-runs path uses the underlying request helper today.
const run = await client._request({
  method: 'POST',
  path: \`/v1/namespaces/my-docs/eval-sets/\${setId}/runs\`,
  body: {
    inference: { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
    embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
    pass_threshold: 4,
  },
});
console.log(\`\${run.num_passed}/\${run.num_questions} passed\`);`),
    pythonSdk(`    run = client._http.request(
        "POST",
        f"/v1/namespaces/my-docs/eval-sets/{set_id}/runs",
        json={
            "inference": {"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
            "embedding": {"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
            "pass_threshold": 4,
        },
    )
    print(f"{run['num_passed']}/{run['num_questions']} passed")`),
  ],
};

// ─── 14. DLQ retry (admin) ────────────────────────────────────────
const DLQ_RETRY: SampleEntry = {
  key: { method: 'post', path: '/v1/ingestion-jobs/{id}/retry' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Requires admin scope on the API key.
curl -X POST "${URL_}/v1/ingestion-jobs/$JOB_ID/retry" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{}'

# Returns 400 DLQ_NOT_DEAD_LETTERED if the job isn't actually DLQ'd.
# Returns 404 DLQ_NOT_FOUND if the job is not visible to your tenant.`,
    },
    nodeSdk(`import { TextralClient, TextralApiError } from '@textral/sdk';
const client = new TextralClient({ profile: 'admin' });

try {
  await client.ingestionJobs.retry(jobId);
  console.log('re-enqueued');
} catch (e) {
  if (e instanceof TextralApiError) {
    console.error(\`retry failed: \${e.code} — \${e.message}\`);
  } else throw e;
}`),
    pythonSdk(`    # Requires the 'admin' profile (admin-scoped API key).
    from textral import TextralAPIError
    try:
        client.ingestion_jobs.retry(job_id)
        print("re-enqueued")
    except TextralAPIError as e:
        print(f"retry failed: {e.code} — {e.message}")`),
  ],
};

// ─── 15. List dead-lettered jobs (admin) ──────────────────────────
const LIST_DLQ: SampleEntry = {
  key: { method: 'get', path: '/v1/admin/ingestion-jobs' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -s "${URL_}/v1/admin/ingestion-jobs?dead_lettered=1&limit=50" \\
  -H "X-Textral-Api-Key: ${KEY}"

# Cursor-paginate via &cursor=<created_at>.`,
    },
    nodeSdk(`// iterateFailingJobs() walks every page transparently.
for await (const job of client.admin.iterateFailingJobs({ limit: 50 })) {
  console.log(job.id, job.error_code, job.error_message);
}`),
    pythonSdk(`    # iterate_failing_jobs() walks every page transparently.
    for job in client.admin.iterate_failing_jobs(limit=50):
        print(job["id"], job.get("error_code"), job.get("error_message"))`),
  ],
};

const ALL_SAMPLES: SampleEntry[] = [
  ME,
  REG_PROVIDER_KEY,
  REG_NAMESPACE,
  REG_DOCUMENT,
  UPLOAD_BYTES,
  FINALIZE_UPLOAD,
  INGEST,
  POLL_JOB,
  SYNC_QUERY,
  BULK_INGEST,
  REG_EVAL_SET,
  RUN_EVAL,
  DLQ_RETRY,
  LIST_DLQ,
];

interface SpecLikeForSamples {
  paths?: Record<string, Record<string, { 'x-codeSamples'?: CodeSample[] } & Record<string, unknown>>>;
}

/** Walks the OpenAPI spec and attaches `x-codeSamples` to every flagship
 *  operation. Streaming samples are appended onto the sync query
 *  operation since both share `(POST, /v1/query)`. */
export function applyCodeSamples(spec: SpecLikeForSamples): void {
  if (!spec.paths) return;
  for (const entry of ALL_SAMPLES) {
    const ops = spec.paths[entry.key.path];
    if (!ops) continue;
    const op = ops[entry.key.method];
    if (!op) continue;
    op['x-codeSamples'] = entry.samples;
  }
  // Streaming samples + cookbook patterns augment the sync /v1/query operation.
  const queryOp = spec.paths['/v1/query']?.post;
  if (queryOp && Array.isArray(queryOp['x-codeSamples'])) {
    queryOp['x-codeSamples'] = [
      ...(queryOp['x-codeSamples'] as CodeSample[]),
      ...STREAMING_QUERY_SAMPLE,
      ...COOKBOOK_STRUCTURED_SIMPLE,
      ...COOKBOOK_STRUCTURED_NESTED,
      ...COOKBOOK_DOC_SUBSET,
      ...COOKBOOK_CUSTOM_PROMPT,
      ...COOKBOOK_FAILURE_RECOVERY,
      ...COOKBOOK_TOKEN_BUDGET,
    ];
  }
  // Named examples on the POST /v1/query request body — Scalar
  // surfaces these as a dropdown above the request body editor in
  // the Try-It panel.
  applyQueryRequestExamples(spec);
}

interface OperationWithBodyExamples {
  requestBody?: {
    content?: {
      'application/json'?: {
        examples?: Record<string, { summary: string; value: unknown }>;
      };
    };
  };
}

function applyQueryRequestExamples(spec: SpecLikeForSamples): void {
  if (!spec.paths) return;
  const op = spec.paths['/v1/query']?.post as OperationWithBodyExamples | undefined;
  if (!op?.requestBody?.content?.['application/json']) return;
  const baseEmbedding = {
    provider: 'openai',
    model: 'text-embedding-3-large',
    dimensions: 1536,
    provider_key_ref: 'default',
  };
  const baseInference = {
    provider: 'openai',
    model: 'gpt-4o-mini',
    provider_key_ref: 'default',
  };
  const baseChunking = { profile: 'generic' };
  const baseRetrieval = { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 };

  op.requestBody.content['application/json'].examples = {
    minimal: {
      summary: '1. Minimal RAG',
      value: {
        namespace: 'my-docs',
        query: 'What does the doc say about X?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
      },
    },
    structured_simple: {
      summary: '2. Structured (simple)',
      value: {
        namespace: 'my-docs',
        query: 'Name two scholars connected to Alexandria.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        output: {
          mode: 'structured',
          schema: {
            type: 'object',
            properties: { scholars: { type: 'array', items: { type: 'string' } } },
            required: ['scholars'],
            additionalProperties: false,
          },
        },
      },
    },
    structured_nested: {
      summary: '3. Structured (nested + citations)',
      value: {
        namespace: 'my-docs',
        query: 'List the scholars mentioned and what each is known for.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        output: {
          mode: 'structured',
          schema: {
            type: 'object',
            properties: {
              scholars: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: { name: { type: 'string' }, known_for: { type: 'string' } },
                  required: ['name', 'known_for'],
                  additionalProperties: false,
                },
              },
              citations: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: { chunk_id: { type: 'string' }, quote: { type: 'string' } },
                  required: ['chunk_id', 'quote'],
                  additionalProperties: false,
                },
              },
            },
            required: ['scholars', 'citations'],
            additionalProperties: false,
          },
        },
      },
    },
    document_subset: {
      summary: '5. Document subset',
      value: {
        namespace: 'my-docs',
        document_ids: ['doc_01HABC...', 'doc_01HDEF...'],
        query: 'What does this contract say about termination?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: { ...baseRetrieval, top_k_dense: 10, top_k_sparse: 10 },
      },
    },
    custom_prompt: {
      summary: '6. Custom system prompt',
      value: {
        namespace: 'my-docs',
        query: 'Who was Eratosthenes?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        prompt: {
          system: 'You are a careful research assistant. Reply in two sentences max.',
        },
      },
    },
    token_budget: {
      summary: '8. Token-budget tweak',
      value: {
        namespace: 'my-docs',
        query: 'Summarise the corpus in two sentences.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        context: { max_context_tokens: 1500 },
      },
    },
  };
}

/** Exported so the regression test can pin the keys. */
export const FLAGSHIP_OPERATION_KEYS: SampleKey[] = ALL_SAMPLES.map((e) => e.key);
