// Hand-crafted code samples for the flagship endpoints.
//
// Per docs/SCALAR_DOCS_ENHANCEMENT_PLAN.md §10. Each entry is keyed by
// (method, path). At spec-render time, applyCodeSamples() walks the
// generated OpenAPI doc and attaches `x-codeSamples` to the matching
// operation. operationIds are auto-generated by @hono/zod-openapi, so
// keying by (method, path) is the durable contract.
//
// Languages: shell (curl), js (TS via fetch), python (requests).
// Each sample uses two placeholder strings the user replaces:
//   {{TENANT_API_KEY}}  → their own X-Textral-Api-Key
//   {{WORKER_URL}}      → e.g. https://textral-api-dev.<sub>.workers.dev

export interface CodeSample {
  lang: 'shell' | 'js' | 'python';
  label: string;
  source: string;
}

export interface SampleKey {
  method: 'get' | 'post' | 'put' | 'delete' | 'patch';
  path: string;
}

interface SampleEntry {
  key: SampleKey;
  samples: CodeSample[];
}

const KEY = '{{TENANT_API_KEY}}';
const URL_ = '{{WORKER_URL}}';

// ─── 1. Auth sanity check ──────────────────────────────────────────
const ME: SampleEntry = {
  key: { method: 'get', path: '/v1/me' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -s "${URL_}/v1/me" \\
  -H "X-Textral-Api-Key: ${KEY}"`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const res = await fetch(\`\${WORKER_URL}/v1/me\`, {
  headers: { 'X-Textral-Api-Key': API_KEY },
});
const me = await res.json();
console.log(me.tenant_id);`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `import requests
r = requests.get(
    f"{WORKER_URL}/v1/me",
    headers={"X-Textral-Api-Key": API_KEY},
)
print(r.json()["tenant_id"])`,
    },
  ],
};

// ─── 2. Register a provider key (BYOK) ─────────────────────────────
const REG_PROVIDER_KEY: SampleEntry = {
  key: { method: 'post', path: '/v1/provider-keys' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/provider-keys" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "provider": "openai",
    "label": "default",
    "key": "sk-..."
  }'`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const res = await fetch(\`\${WORKER_URL}/v1/provider-keys\`, {
  method: 'POST',
  headers: {
    'X-Textral-Api-Key': API_KEY,
    'content-type': 'application/json',
  },
  body: JSON.stringify({
    provider: 'openai',
    label: 'default',
    key: process.env.OPENAI_API_KEY,
  }),
});
const { id } = await res.json(); // pkey_…`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `import os, requests
r = requests.post(
    f"{WORKER_URL}/v1/provider-keys",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={"provider": "openai", "label": "default", "key": os.environ["OPENAI_API_KEY"]},
)
print(r.json()["id"])  # pkey_...`,
    },
  ],
};

// ─── 3. Create a namespace ────────────────────────────────────────
const REG_NAMESPACE: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "generic",
    "default_embedding_profile": "openai-text-embedding-3-large-1536"
  }'

# corpus_profile options: generic | narrative | legal | support | technical`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const res = await fetch(\`\${WORKER_URL}/v1/namespaces\`, {
  method: 'POST',
  headers: {
    'X-Textral-Api-Key': API_KEY,
    'content-type': 'application/json',
  },
  body: JSON.stringify({
    slug: 'my-docs',
    corpus_profile: 'generic',
    default_embedding_profile: 'openai-text-embedding-3-large-1536',
  }),
});
const ns = await res.json(); // { id: "ns_…", slug: "my-docs", ... }`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `r = requests.post(
    f"{WORKER_URL}/v1/namespaces",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "slug": "my-docs",
        "corpus_profile": "generic",
        "default_embedding_profile": "openai-text-embedding-3-large-1536",
    },
)
ns = r.json()`,
    },
    // ── V3 Phase 1 — alternate vector backend variants. ──
    {
      lang: 'shell',
      label: 'curl (Qdrant backend)',
      source: `curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "narrative",
    "default_embedding_profile": "openai-text-embedding-3-large-1536",
    "vector_backend": "qdrant",
    "vector_index_name": "my-docs-passages"
  }'

# Adapter auto-creates the Qdrant collection with size=dimensions and
# cosine distance. Operator must set QDRANT_URL on the deploy.`,
    },
    {
      lang: 'shell',
      label: 'curl (Pinecone backend)',
      source: `# 1) Pre-provision a serverless index in the Pinecone console
#    (dimensions=1536, cosine). Copy the host URL it shows.
# 2) Set PINECONE_API_KEY on the deploy via wrangler secret put.
# 3) Create the namespace pointing at the host:
curl -X POST "${URL_}/v1/namespaces" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "slug": "my-docs",
    "corpus_profile": "narrative",
    "default_embedding_profile": "openai-text-embedding-3-large-1536",
    "vector_backend": "pinecone",
    "vector_index_name": "https://my-idx-xxxxx.svc.us-east-1-aws.pinecone.io"
  }'`,
    },
  ],
};

// ─── 4. Register a document ───────────────────────────────────────
const REG_DOCUMENT: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces/{slug}/documents' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/documents" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "title": "API Reference",
    "doc_type": "technical"
  }'`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const res = await fetch(\`\${WORKER_URL}/v1/namespaces/my-docs/documents\`, {
  method: 'POST',
  headers: {
    'X-Textral-Api-Key': API_KEY,
    'content-type': 'application/json',
  },
  body: JSON.stringify({ title: 'API Reference', doc_type: 'technical' }),
});
const doc = await res.json(); // { id: "doc_…", ... }`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `r = requests.post(
    f"{WORKER_URL}/v1/namespaces/my-docs/documents",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={"title": "API Reference", "doc_type": "technical"},
)
doc = r.json()`,
    },
  ],
};

// ─── 5. Upload bytes (presign + PUT, two-step) ────────────────────
const UPLOAD_BYTES: SampleEntry = {
  key: { method: 'post', path: '/v1/documents/{id}/uploads' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Step 1: get the upload URL.
UPLOAD_JSON=$(curl -s -X POST "${URL_}/v1/documents/$DOC_ID/uploads" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "content_type": "text/markdown",
    "size_bytes": '"$(stat -c%s ./mydoc.md)"'
  }')

UPLOAD_URL=$(echo "$UPLOAD_JSON" | jq -r .url)
UPLOAD_ID=$(echo "$UPLOAD_JSON" | jq -r .upload_id)

# Step 2: PUT the bytes (URL points back at the Worker — proxied).
curl -X PUT "$UPLOAD_URL" \\
  -H 'content-type: text/markdown' \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  --data-binary @./mydoc.md

# Step 3: see the finalize sample.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const stat = await Deno.stat('./mydoc.md');  // or fs.stat in Node
const upload = await fetch(\`\${WORKER_URL}/v1/documents/\${docId}/uploads\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({ content_type: 'text/markdown', size_bytes: stat.size }),
}).then((r) => r.json());

await fetch(upload.url, {
  method: 'PUT',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'text/markdown' },
  body: await Deno.readFile('./mydoc.md'),
});
// Then call .../finalize.`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `import os
size = os.path.getsize("./mydoc.md")
upload = requests.post(
    f"{WORKER_URL}/v1/documents/{doc_id}/uploads",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={"content_type": "text/markdown", "size_bytes": size},
).json()

with open("./mydoc.md", "rb") as f:
    requests.put(
        upload["url"],
        headers={"X-Textral-Api-Key": API_KEY, "content-type": "text/markdown"},
        data=f,
    )

# Then call .../finalize.`,
    },
  ],
};

// ─── 6. Finalize upload ───────────────────────────────────────────
const FINALIZE_UPLOAD: SampleEntry = {
  key: {
    method: 'post',
    path: '/v1/documents/{id}/uploads/{upload_id}/finalize',
  },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/documents/$DOC_ID/uploads/$UPLOAD_ID/finalize" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{}'

# Returns version_id; pass it to /ingest.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const finalize = await fetch(
  \`\${WORKER_URL}/v1/documents/\${docId}/uploads/\${uploadId}/finalize\`,
  {
    method: 'POST',
    headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
    body: '{}',
  },
).then((r) => r.json());
const versionId = finalize.version_id;`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `f = requests.post(
    f"{WORKER_URL}/v1/documents/{doc_id}/uploads/{upload_id}/finalize",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={},
).json()
version_id = f["version_id"]`,
    },
  ],
};

// ─── 7. Trigger ingestion ─────────────────────────────────────────
const INGEST: SampleEntry = {
  key: { method: 'post', path: '/v1/documents/{id}/ingest' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Minimal RAG path: generic profile, default chunking, mode=full.
curl -X POST "${URL_}/v1/documents/$DOC_ID/ingest" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "version_id": "'"$VERSION_ID"'",
    "embedding": {
      "provider": "openai",
      "model": "text-embedding-3-large",
      "dimensions": 1536,
      "provider_key_ref": "default"
    },
    "chunking": { "profile": "generic" },
    "mode": "full"
  }'

# Returns job_id; poll GET /v1/ingestion-jobs/{id} until status=completed.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const ingest = await fetch(\`\${WORKER_URL}/v1/documents/\${docId}/ingest\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({
    version_id: versionId,
    embedding: {
      provider: 'openai',
      model: 'text-embedding-3-large',
      dimensions: 1536,
      provider_key_ref: 'default',
    },
    chunking: { profile: 'generic' },
    mode: 'full',
  }),
}).then((r) => r.json());
const jobId = ingest.job_id;`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `r = requests.post(
    f"{WORKER_URL}/v1/documents/{doc_id}/ingest",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "version_id": version_id,
        "embedding": {
            "provider": "openai",
            "model": "text-embedding-3-large",
            "dimensions": 1536,
            "provider_key_ref": "default",
        },
        "chunking": {"profile": "generic"},
        "mode": "full",
    },
)
job_id = r.json()["job_id"]`,
    },
  ],
};

// ─── 8. Poll an ingestion job ─────────────────────────────────────
const POLL_JOB: SampleEntry = {
  key: { method: 'get', path: '/v1/ingestion-jobs/{id}' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Polling loop (simplified).
while true; do
  STATUS=$(curl -s "${URL_}/v1/ingestion-jobs/$JOB_ID" \\
    -H "X-Textral-Api-Key: ${KEY}" | jq -r .status)
  echo "status: $STATUS"
  case "$STATUS" in
    completed|failed) break ;;
    *) sleep 5 ;;
  esac
done`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `async function pollJob(jobId: string, timeoutMs = 240_000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const r = await fetch(\`\${WORKER_URL}/v1/ingestion-jobs/\${jobId}\`, {
      headers: { 'X-Textral-Api-Key': API_KEY },
    }).then((r) => r.json());
    if (r.status === 'completed' || r.status === 'failed') return r;
    await new Promise((rs) => setTimeout(rs, 5_000));
  }
  throw new Error('job poll timed out');
}`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `import time
def poll_job(job_id, timeout_s=240):
    start = time.time()
    while time.time() - start < timeout_s:
        r = requests.get(
            f"{WORKER_URL}/v1/ingestion-jobs/{job_id}",
            headers={"X-Textral-Api-Key": API_KEY},
        ).json()
        if r["status"] in ("completed", "failed"):
            return r
        time.sleep(5)
    raise TimeoutError("job poll timed out")`,
    },
  ],
};

// ─── 9. Sync query ────────────────────────────────────────────────
const SYNC_QUERY: SampleEntry = {
  key: { method: 'post', path: '/v1/query' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Minimal query body — generic profile, hybrid retrieval.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does the doc say about X?",
    "embedding": {
      "provider": "openai",
      "model": "text-embedding-3-large",
      "dimensions": 1536,
      "provider_key_ref": "default"
    },
    "inference": {
      "provider": "openai",
      "model": "gpt-4o-mini",
      "provider_key_ref": "default"
    },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 }
  }'

# Append ?stream=sse for Server-Sent Events streaming.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const res = await fetch(\`\${WORKER_URL}/v1/query\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({
    namespace: 'my-docs',
    query: 'What does the doc say about X?',
    embedding: {
      provider: 'openai',
      model: 'text-embedding-3-large',
      dimensions: 1536,
      provider_key_ref: 'default',
    },
    inference: {
      provider: 'openai',
      model: 'gpt-4o-mini',
      provider_key_ref: 'default',
    },
    chunking: { profile: 'generic' },
    retrieval: { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
  }),
}).then((r) => r.json());
console.log(res.answer.text, res.citations, res.audit);`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `r = requests.post(
    f"{WORKER_URL}/v1/query",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "namespace": "my-docs",
        "query": "What does the doc say about X?",
        "embedding": {
            "provider": "openai",
            "model": "text-embedding-3-large",
            "dimensions": 1536,
            "provider_key_ref": "default",
        },
        "inference": {
            "provider": "openai",
            "model": "gpt-4o-mini",
            "provider_key_ref": "default",
        },
        "chunking": {"profile": "generic"},
        "retrieval": {"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
    },
).json()
print(r["answer"]["text"], r["citations"], r["audit"]["degradation_level"])`,
    },
  ],
};

// ─── 10. Streaming query (SSE) ────────────────────────────────────
// Same path as #9 but with ?stream=sse — Scalar shows it as a
// separate operation only if we register it as one. For now we
// document it inside the sync query's description and as a
// snippet here keyed on the same path; the renderer dedupes by
// (path, method) so we attach this as an *additional* sample on
// the sync query.
const STREAMING_QUERY_SAMPLE: CodeSample[] = [
  {
    lang: 'shell',
    label: 'curl (?stream=sse)',
    source: `curl -N -X POST "${URL_}/v1/query?stream=sse" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'accept: text/event-stream' \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does the doc say about X?",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 }
  }'

# Two event types: token (per delta) and done (single final event).`,
  },
  {
    lang: 'js',
    label: 'TypeScript (fetch + SSE)',
    source: `const res = await fetch(\`\${WORKER_URL}/v1/query?stream=sse\`, {
  method: 'POST',
  headers: {
    'X-Textral-Api-Key': API_KEY,
    'accept': 'text/event-stream',
    'content-type': 'application/json',
  },
  body: JSON.stringify({ /* same as sync query body */ }),
});
const reader = res.body!.getReader();
const dec = new TextDecoder();
let buf = '';
while (true) {
  const { value, done } = await reader.read();
  if (done) break;
  buf += dec.decode(value, { stream: true });
  let idx;
  while ((idx = buf.indexOf('\\n\\n')) >= 0) {
    const frame = buf.slice(0, idx); buf = buf.slice(idx + 2);
    // frame: "event: token\\ndata: {...}"  or  "event: done\\ndata: {...}"
    console.log(frame);
  }
}`,
  },
  {
    lang: 'python',
    label: 'Python (requests + SSE)',
    source: `import json, requests
with requests.post(
    f"{WORKER_URL}/v1/query?stream=sse",
    headers={
        "X-Textral-Api-Key": API_KEY,
        "accept": "text/event-stream",
        "content-type": "application/json",
    },
    json={ "namespace": "my-docs", "query": "...", "embedding": {...}, "inference": {...},
           "chunking": {"profile": "generic"},
           "retrieval": {"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5} },
    stream=True,
) as r:
    buf = ""
    for chunk in r.iter_content(chunk_size=None, decode_unicode=True):
        buf += chunk
        while "\\n\\n" in buf:
            frame, buf = buf.split("\\n\\n", 1)
            event = next((l[7:] for l in frame.split("\\n") if l.startswith("event: ")), "")
            data = next((l[6:] for l in frame.split("\\n") if l.startswith("data: ")), "")
            if event == "token":
                print(json.loads(data)["text"], end="", flush=True)
            elif event == "done":
                done = json.loads(data)
                print(f"\\n[done — degradation={done['degradation_level']}]")`,
  },
];

// ─── Cookbook patterns (attached as additional samples on POST /v1/query) ──

const COOKBOOK_STRUCTURED_SIMPLE: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 2: structured (simple)',
    source: `# Constrain output to a JSON schema. answer.object comes back parsed.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Name two scholars connected to Alexandria.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "output": {
      "mode": "structured",
      "schema": {
        "type": "object",
        "properties": {
          "scholars": { "type": "array", "items": { "type": "string" } }
        },
        "required": ["scholars"],
        "additionalProperties": false
      }
    }
  }'
# Response: answer.mode = "structured", answer.object = { "scholars": [...] }
# Note: omitting a "citations" field in the schema means top-level citations[] will be empty.`,
  },
  {
    lang: 'js',
    label: 'Pattern 2: structured (simple)',
    source: `const res = await fetch(\`\${WORKER_URL}/v1/query\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({
    namespace: 'my-docs',
    query: 'Name two scholars connected to Alexandria.',
    embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
    inference: { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
    chunking: { profile: 'generic' },
    retrieval: { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
    output: {
      mode: 'structured',
      schema: {
        type: 'object',
        properties: { scholars: { type: 'array', items: { type: 'string' } } },
        required: ['scholars'],
        additionalProperties: false,
      },
    },
  }),
}).then((r) => r.json());
if (res.answer.mode === 'structured') {
  const obj = res.answer.object as { scholars: string[] };
  console.log(obj.scholars);
}`,
  },
  {
    lang: 'python',
    label: 'Pattern 2: structured (simple)',
    source: `r = requests.post(
    f"{WORKER_URL}/v1/query",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "namespace": "my-docs",
        "query": "Name two scholars connected to Alexandria.",
        "embedding": {"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        "inference": {"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        "chunking": {"profile": "generic"},
        "retrieval": {"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
        "output": {
            "mode": "structured",
            "schema": {
                "type": "object",
                "properties": {"scholars": {"type": "array", "items": {"type": "string"}}},
                "required": ["scholars"],
                "additionalProperties": False,
            },
        },
    },
).json()
print(r["answer"]["object"]["scholars"])`,
  },
];

const COOKBOOK_STRUCTURED_NESTED: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 3: structured (nested + citations)',
    source: `# Schema with a top-level citations[] field round-trips:
# the platform filters citations to retrieved chunks and
# also resolves them into the response's top-level citations[].
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "List the scholars mentioned and what each is known for.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "output": {
      "mode": "structured",
      "schema": {
        "type": "object",
        "properties": {
          "scholars": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": { "name": { "type": "string" }, "known_for": { "type": "string" } },
              "required": ["name", "known_for"],
              "additionalProperties": false
            }
          },
          "citations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": { "chunk_id": { "type": "string" }, "quote": { "type": "string" } },
              "required": ["chunk_id", "quote"],
              "additionalProperties": false
            }
          }
        },
        "required": ["scholars", "citations"],
        "additionalProperties": false
      }
    }
  }'
# Gotcha: OpenAI strict mode requires every property in 'required'.
# If "quote" were optional here, synthesis would fail with
# degradation_level=cannot_answer.`,
  },
  {
    lang: 'js',
    label: 'Pattern 3: structured (nested + citations)',
    source: `const schema = {
  type: 'object',
  properties: {
    scholars: {
      type: 'array',
      items: {
        type: 'object',
        properties: { name: { type: 'string' }, known_for: { type: 'string' } },
        required: ['name', 'known_for'],
        additionalProperties: false,
      },
    },
    citations: {
      type: 'array',
      items: {
        type: 'object',
        properties: { chunk_id: { type: 'string' }, quote: { type: 'string' } },
        required: ['chunk_id', 'quote'],   // strict mode requires both
        additionalProperties: false,
      },
    },
  },
  required: ['scholars', 'citations'],
  additionalProperties: false,
};

const res = await fetch(\`\${WORKER_URL}/v1/query\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({
    namespace: 'my-docs',
    query: 'List the scholars mentioned and what each is known for.',
    embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
    inference: { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
    chunking: { profile: 'generic' },
    retrieval: { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 },
    output: { mode: 'structured', schema },
  }),
}).then((r) => r.json());
console.log(res.answer.object.scholars);
console.log('top-level citations:', res.citations);`,
  },
  {
    lang: 'python',
    label: 'Pattern 3: structured (nested + citations)',
    source: `schema = {
    "type": "object",
    "properties": {
        "scholars": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"name": {"type": "string"}, "known_for": {"type": "string"}},
                "required": ["name", "known_for"],
                "additionalProperties": False,
            },
        },
        "citations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"chunk_id": {"type": "string"}, "quote": {"type": "string"}},
                "required": ["chunk_id", "quote"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["scholars", "citations"],
    "additionalProperties": False,
}
r = requests.post(
    f"{WORKER_URL}/v1/query",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "namespace": "my-docs",
        "query": "List the scholars mentioned and what each is known for.",
        "embedding": {"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        "inference": {"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        "chunking": {"profile": "generic"},
        "retrieval": {"strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5},
        "output": {"mode": "structured", "schema": schema},
    },
).json()
print(r["answer"]["object"]["scholars"])
print("top-level citations:", r["citations"])`,
  },
];

const COOKBOOK_DOC_SUBSET: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 5: document subset',
    source: `# Scope retrieval to specific documents within the namespace.
# Useful when a tenant has many docs but the query is about a known few.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "What does this contract say about termination?",
    "document_ids": ["doc_01HABC...", "doc_01HDEF..."],
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 10, "top_k_sparse": 10 }
  }'`,
  },
];

const COOKBOOK_CUSTOM_PROMPT: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 6: custom system prompt',
    source: `# Override the corpus profile's default system prompt.
# The platform appends a mandatory citation suffix to your prompt;
# you cannot opt out of citation grounding.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Who was Eratosthenes?",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "prompt": {
      "system": "You are a careful research assistant. Reply in two sentences max."
    }
  }'`,
  },
];

const COOKBOOK_FAILURE_RECOVERY: CodeSample[] = [
  {
    lang: 'js',
    label: 'Pattern 7: cannot-answer recovery',
    source: `// Branch on degradation_level and audit fields to handle each
// failure mode distinctly.
const res = await fetch(\`\${WORKER_URL}/v1/query\`, {
  method: 'POST',
  headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
  body: JSON.stringify({ /* ... */ }),
}).then((r) => r.json());

switch (res.degradation_level) {
  case 'full':
    // Citations + answer, all integrity checks pass.
    return res.answer;
  case 'partial':
    // Some citations dropped — show with a warning.
    return { ...res.answer, warning: 'some citations were dropped' };
  case 'no_citations':
    // Model didn't cite or retrieval missed. Try again with rerank
    // enabled (if the namespace's profile supports it) or a stronger model.
    if (!res.audit.reranker.executed) {
      return retryWithStrongerModel();
    }
    return { ...res.answer, warning: 'answer not citation-grounded' };
  case 'cannot_answer':
    // Synthesis failed. Inspect audit.synthesis_status; common: provider
    // quota / strict-mode schema rejection / empty corpus.
    console.error('cannot_answer; query_event:', res.query_event_id);
    return { error: 'answer unavailable' };
}`,
  },
  {
    lang: 'python',
    label: 'Pattern 7: cannot-answer recovery',
    source: `r = requests.post(f"{WORKER_URL}/v1/query", headers={...}, json={...}).json()
deg = r["degradation_level"]

if deg == "full":
    return r["answer"]
elif deg == "partial":
    return {**r["answer"], "warning": "some citations were dropped"}
elif deg == "no_citations":
    if not r["audit"]["reranker"]["executed"]:
        return retry_with_stronger_model()
    return {**r["answer"], "warning": "answer not citation-grounded"}
elif deg == "cannot_answer":
    print(f"cannot_answer; query_event: {r['query_event_id']}")
    return {"error": "answer unavailable"}`,
  },
];

const COOKBOOK_TOKEN_BUDGET: CodeSample[] = [
  {
    lang: 'shell',
    label: 'Pattern 8: token budget tweak',
    source: `# Tighten context.max_context_tokens for cheap models or
# latency-sensitive paths. Default is 12000.
curl -X POST "${URL_}/v1/query" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "namespace": "my-docs",
    "query": "Summarise the corpus in two sentences.",
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "chunking": { "profile": "generic" },
    "retrieval": { "strategy": "hybrid_rrf", "top_k_dense": 5, "top_k_sparse": 5 },
    "context": { "max_context_tokens": 1500 }
  }'`,
  },
];

// ─── 11. Register an eval set ─────────────────────────────────────
const REG_EVAL_SET: SampleEntry = {
  key: { method: 'post', path: '/v1/namespaces/{slug}/eval-sets' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/eval-sets" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "name": "baseline-v1",
    "questions": [
      { "question": "What does the doc say about X?",
        "expected_answer": "It says foo." },
      { "question": "Who wrote it?" }
    ]
  }'`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const set = await fetch(
  \`\${WORKER_URL}/v1/namespaces/my-docs/eval-sets\`,
  {
    method: 'POST',
    headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
    body: JSON.stringify({
      name: 'baseline-v1',
      questions: [
        { question: 'What does the doc say about X?', expected_answer: 'It says foo.' },
        { question: 'Who wrote it?' },
      ],
    }),
  },
).then((r) => r.json());
const setId = set.id;`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `s = requests.post(
    f"{WORKER_URL}/v1/namespaces/my-docs/eval-sets",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "name": "baseline-v1",
        "questions": [
            {"question": "What does the doc say about X?", "expected_answer": "It says foo."},
            {"question": "Who wrote it?"},
        ],
    },
).json()
set_id = s["id"]`,
    },
  ],
};

// ─── 12. Kick off an eval run ─────────────────────────────────────
const RUN_EVAL: SampleEntry = {
  key: {
    method: 'post',
    path: '/v1/namespaces/{slug}/eval-sets/{id}/runs',
  },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -X POST "${URL_}/v1/namespaces/my-docs/eval-sets/$SET_ID/runs" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{
    "inference": { "provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default" },
    "embedding": { "provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default" },
    "pass_threshold": 4
  }'

# Synchronous: returns once every question completes.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const run = await fetch(
  \`\${WORKER_URL}/v1/namespaces/my-docs/eval-sets/\${setId}/runs\`,
  {
    method: 'POST',
    headers: { 'X-Textral-Api-Key': API_KEY, 'content-type': 'application/json' },
    body: JSON.stringify({
      inference: { provider: 'openai', model: 'gpt-4o-mini', provider_key_ref: 'default' },
      embedding: { provider: 'openai', model: 'text-embedding-3-large', dimensions: 1536, provider_key_ref: 'default' },
      pass_threshold: 4,
    }),
  },
).then((r) => r.json());
console.log(\`\${run.num_passed}/\${run.num_questions} passed\`);`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `run = requests.post(
    f"{WORKER_URL}/v1/namespaces/my-docs/eval-sets/{set_id}/runs",
    headers={"X-Textral-Api-Key": API_KEY, "content-type": "application/json"},
    json={
        "inference": {"provider": "openai", "model": "gpt-4o-mini", "provider_key_ref": "default"},
        "embedding": {"provider": "openai", "model": "text-embedding-3-large", "dimensions": 1536, "provider_key_ref": "default"},
        "pass_threshold": 4,
    },
).json()
print(f"{run['num_passed']}/{run['num_questions']} passed")`,
    },
  ],
};

// ─── 13. DLQ retry (admin) ────────────────────────────────────────
const DLQ_RETRY: SampleEntry = {
  key: { method: 'post', path: '/v1/ingestion-jobs/{id}/retry' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `# Requires admin scope on the API key.
curl -X POST "${URL_}/v1/ingestion-jobs/$JOB_ID/retry" \\
  -H "X-Textral-Api-Key: ${KEY}" \\
  -H 'content-type: application/json' \\
  -d '{}'

# Returns 400 DLQ_NOT_DEAD_LETTERED if the job isn't actually DLQ'd.
# Returns 404 DLQ_NOT_FOUND if the job is not visible to your tenant.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const r = await fetch(
  \`\${WORKER_URL}/v1/ingestion-jobs/\${jobId}/retry\`,
  {
    method: 'POST',
    headers: { 'X-Textral-Api-Key': ADMIN_KEY, 'content-type': 'application/json' },
    body: '{}',
  },
);
if (!r.ok) {
  const err = await r.json();
  console.error(\`retry failed: \${err.error.code} — \${err.error.message}\`);
} else {
  console.log('re-enqueued', await r.json());
}`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `r = requests.post(
    f"{WORKER_URL}/v1/ingestion-jobs/{job_id}/retry",
    headers={"X-Textral-Api-Key": ADMIN_KEY, "content-type": "application/json"},
    json={},
)
if not r.ok:
    err = r.json()["error"]
    raise SystemExit(f"retry failed: {err['code']} — {err['message']}")
print("re-enqueued", r.json())`,
    },
  ],
};

// ─── 14. List dead-lettered jobs (admin) ──────────────────────────
const LIST_DLQ: SampleEntry = {
  key: { method: 'get', path: '/v1/admin/ingestion-jobs' },
  samples: [
    {
      lang: 'shell',
      label: 'curl',
      source: `curl -s "${URL_}/v1/admin/ingestion-jobs?dead_lettered=1&limit=50" \\
  -H "X-Textral-Api-Key: ${KEY}"

# Cursor-paginate via &cursor=<created_at>.`,
    },
    {
      lang: 'js',
      label: 'TypeScript (fetch)',
      source: `const list = await fetch(
  \`\${WORKER_URL}/v1/admin/ingestion-jobs?dead_lettered=1&limit=50\`,
  { headers: { 'X-Textral-Api-Key': ADMIN_KEY } },
).then((r) => r.json());
for (const job of list.items) {
  console.log(job.id, job.error_code, job.error_message);
}`,
    },
    {
      lang: 'python',
      label: 'Python (requests)',
      source: `list_ = requests.get(
    f"{WORKER_URL}/v1/admin/ingestion-jobs",
    params={"dead_lettered": "1", "limit": 50},
    headers={"X-Textral-Api-Key": ADMIN_KEY},
).json()
for job in list_["items"]:
    print(job["id"], job["error_code"], job["error_message"])`,
    },
  ],
};

const ALL_SAMPLES: SampleEntry[] = [
  ME,
  REG_PROVIDER_KEY,
  REG_NAMESPACE,
  REG_DOCUMENT,
  UPLOAD_BYTES,
  FINALIZE_UPLOAD,
  INGEST,
  POLL_JOB,
  SYNC_QUERY,
  REG_EVAL_SET,
  RUN_EVAL,
  DLQ_RETRY,
  LIST_DLQ,
];

interface SpecLikeForSamples {
  paths?: Record<string, Record<string, { 'x-codeSamples'?: CodeSample[] } & Record<string, unknown>>>;
}

/** Walks the OpenAPI spec and attaches `x-codeSamples` to every flagship
 *  operation. Streaming samples are appended onto the sync query
 *  operation since both share `(POST, /v1/query)`. */
export function applyCodeSamples(spec: SpecLikeForSamples): void {
  if (!spec.paths) return;
  for (const entry of ALL_SAMPLES) {
    const ops = spec.paths[entry.key.path];
    if (!ops) continue;
    const op = ops[entry.key.method];
    if (!op) continue;
    op['x-codeSamples'] = entry.samples;
  }
  // Streaming samples + cookbook patterns augment the sync /v1/query operation.
  const queryOp = spec.paths['/v1/query']?.post;
  if (queryOp && Array.isArray(queryOp['x-codeSamples'])) {
    queryOp['x-codeSamples'] = [
      ...(queryOp['x-codeSamples'] as CodeSample[]),
      ...STREAMING_QUERY_SAMPLE,
      ...COOKBOOK_STRUCTURED_SIMPLE,
      ...COOKBOOK_STRUCTURED_NESTED,
      ...COOKBOOK_DOC_SUBSET,
      ...COOKBOOK_CUSTOM_PROMPT,
      ...COOKBOOK_FAILURE_RECOVERY,
      ...COOKBOOK_TOKEN_BUDGET,
    ];
  }
  // Named examples on the POST /v1/query request body — Scalar
  // surfaces these as a dropdown above the request body editor in
  // the Try-It panel.
  applyQueryRequestExamples(spec);
}

interface OperationWithBodyExamples {
  requestBody?: {
    content?: {
      'application/json'?: {
        examples?: Record<string, { summary: string; value: unknown }>;
      };
    };
  };
}

function applyQueryRequestExamples(spec: SpecLikeForSamples): void {
  if (!spec.paths) return;
  const op = spec.paths['/v1/query']?.post as OperationWithBodyExamples | undefined;
  if (!op?.requestBody?.content?.['application/json']) return;
  const baseEmbedding = {
    provider: 'openai',
    model: 'text-embedding-3-large',
    dimensions: 1536,
    provider_key_ref: 'default',
  };
  const baseInference = {
    provider: 'openai',
    model: 'gpt-4o-mini',
    provider_key_ref: 'default',
  };
  const baseChunking = { profile: 'generic' };
  const baseRetrieval = { strategy: 'hybrid_rrf', top_k_dense: 5, top_k_sparse: 5 };

  op.requestBody.content['application/json'].examples = {
    basic: {
      summary: '1. Basic Q&A',
      value: {
        namespace: 'my-docs',
        query: 'What does the doc say about X?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
      },
    },
    structured_simple: {
      summary: '2. Structured (simple)',
      value: {
        namespace: 'my-docs',
        query: 'Name two scholars connected to Alexandria.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        output: {
          mode: 'structured',
          schema: {
            type: 'object',
            properties: {
              scholars: { type: 'array', items: { type: 'string' } },
            },
            required: ['scholars'],
            additionalProperties: false,
          },
        },
      },
    },
    structured_nested: {
      summary: '3. Structured (nested + citations)',
      value: {
        namespace: 'my-docs',
        query: 'List the scholars mentioned and what each is known for.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        output: {
          mode: 'structured',
          schema: {
            type: 'object',
            properties: {
              scholars: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: { name: { type: 'string' }, known_for: { type: 'string' } },
                  required: ['name', 'known_for'],
                  additionalProperties: false,
                },
              },
              citations: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: { chunk_id: { type: 'string' }, quote: { type: 'string' } },
                  required: ['chunk_id', 'quote'],
                  additionalProperties: false,
                },
              },
            },
            required: ['scholars', 'citations'],
            additionalProperties: false,
          },
        },
      },
    },
    document_subset: {
      summary: '5. Document subset',
      value: {
        namespace: 'my-docs',
        document_ids: ['doc_01HABC...', 'doc_01HDEF...'],
        query: 'What does this contract say about termination?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: { ...baseRetrieval, top_k_dense: 10, top_k_sparse: 10 },
      },
    },
    custom_prompt: {
      summary: '6. Custom system prompt',
      value: {
        namespace: 'my-docs',
        query: 'Who was Eratosthenes?',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        prompt: {
          system: 'You are a careful research assistant. Reply in two sentences max.',
        },
      },
    },
    token_budget: {
      summary: '8. Token-budget tweak',
      value: {
        namespace: 'my-docs',
        query: 'Summarise the corpus in two sentences.',
        embedding: baseEmbedding,
        inference: baseInference,
        chunking: baseChunking,
        retrieval: baseRetrieval,
        context: { max_context_tokens: 1500 },
      },
    },
  };
}

/** Exported so the regression test can pin the keys. */
export const FLAGSHIP_OPERATION_KEYS: SampleKey[] = ALL_SAMPLES.map((e) => e.key);
