// Reads packages/{sdk,sdk-python}/README.md and emits an inlined
// `apps/api/src/openapi/sdk-readmes.gen.ts` for the spec extension
// to consume at render time.
//
// The Worker runtime has no filesystem; transclusion has to happen
// at build time. Same shape as packages/sdk-python/codegen/generate.py:
// codegen step → committed artifact → drift check in CI.
//
// Run automatically by:
//   - `pnpm --filter @textral/api dev`   (predev hook)
//   - `pnpm --filter @textral/api build` (prebuild hook)
//   - `pnpm --filter @textral/api test`  (pretest hook)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..');

function read(p: string): string {
  return readFileSync(resolve(ROOT, p), 'utf8');
}

const NODE_README = read('packages/sdk/README.md');
const PYTHON_README = read('packages/sdk-python/README.md');

const NODE_VERSION = (
  JSON.parse(read('packages/sdk/package.json')) as { version: string }
).version;

const pyVersionMatch = read('packages/sdk-python/src/textral/_version.py').match(
  /__version__\s*=\s*"([^"]+)"/,
);
if (!pyVersionMatch) {
  throw new Error('build-sdk-readmes: failed to parse Python SDK version');
}
const PYTHON_VERSION = pyVersionMatch[1];

const out = `// AUTO-GENERATED by apps/api/scripts/build-sdk-readmes.ts.
// Do not edit by hand. Re-runs on every \`pnpm dev\` / \`pnpm build\` /
// \`pnpm test\` via the package's prebuild/predev/pretest hooks.
//
// Sources:
//   - packages/sdk/README.md
//   - packages/sdk-python/README.md
//   - packages/sdk/package.json (version)
//   - packages/sdk-python/src/textral/_version.py (version)

export const SDK_NODE_README = ${JSON.stringify(NODE_README)};
export const SDK_NODE_VERSION = ${JSON.stringify(NODE_VERSION)};

export const SDK_PYTHON_README = ${JSON.stringify(PYTHON_README)};
export const SDK_PYTHON_VERSION = ${JSON.stringify(PYTHON_VERSION)};
`;

writeFileSync(resolve(HERE, '../src/openapi/sdk-readmes.gen.ts'), out);
console.log(
  `[build-sdk-readmes] wrote sdk-readmes.gen.ts (Node ${NODE_VERSION}, Python ${PYTHON_VERSION})`,
);
