# generated by datamodel-codegen:
#   filename:  Answer.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, RootModel


class Answer1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["text"]
    text: str


class Answer2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["structured"]
    object: Any | None = None
    raw: str | None = None


class Answer(RootModel[Answer1 | Answer2]):
    root: Answer1 | Answer2
