# generated by datamodel-codegen:
#   filename:  AuthOkResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class AuthOkResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ok: Literal[True]
