# generated by datamodel-codegen:
#   filename:  BulkOnExisting.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class BulkOnExisting(RootModel[Literal["skip_if_unchanged", "new_version", "replace_current"]]):
    root: Literal["skip_if_unchanged", "new_version", "replace_current"]
