# generated by datamodel-codegen:
#   filename:  BulkJobFileListResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ordinal: int
    filename: str
    size_bytes: int
    content_type: str
    state: str
    document_id: str | None
    version_id: str | None
    ingestion_job_id: str | None
    error_code: str | None
    error_detail: str | None


class BulkJobFileListResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    data: list[Datum]
    next_cursor: str | None
