# generated by datamodel-codegen:
#   filename:  BulkJobListResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Counts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    pending: int
    uploaded: int
    finalized: int
    enqueued: int
    processing: int
    succeeded: int
    failed: int
    skipped: int


class FirstFailure(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ordinal: int
    filename: str
    error_code: str
    error_detail: str | None = None


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    bulk_job_id: str
    state: str
    namespace: str
    total_files: int
    counts: Counts
    progress_pct: Annotated[int, Field(ge=0, le=100)]
    first_failure: FirstFailure | None
    source: Literal["api", "mcp", "sandbox"]
    created_at: int
    finalized_at: int | None
    completed_at: int | None
    audit_query_event_filter: str


class BulkJobListResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    data: list[Datum]
    next_cursor: str | None
