# generated by datamodel-codegen:
#   filename:  BulkSource.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class BulkSource(RootModel[Literal["api", "mcp", "sandbox"]]):
    root: Literal["api", "mcp", "sandbox"]
