# generated by datamodel-codegen:
#   filename:  BulkJobFirstFailure.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class BulkJobFirstFailure(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ordinal: int
    filename: str
    error_code: str
    error_detail: str | None = None
