# generated by datamodel-codegen:
#   filename:  BulkConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Embedding(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
    model: Annotated[str, Field(min_length=1)]
    dimensions: Annotated[int | None, Field(gt=0)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class Chunking(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    profile: str | None = "generic"
    target_tokens: Annotated[int | None, Field(gt=0)] = 600
    overlap_tokens: Annotated[int | None, Field(ge=0)] = 80
    boundary_depth: Annotated[int | None, Field(ge=0)] = 2


class Indexing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    replace_existing_vectors: bool | None = False
    artifact_types: list[str] | None = ["passage"]


class Provider(
    RootModel[Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]]
):
    root: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]


class DefaultModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
    model: Annotated[str, Field(min_length=1)]
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class Pass(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: Annotated[str, Field(min_length=1)]
    enabled: bool | None = True
    required: bool | None = False
    model: DefaultModel | None = None


class Enrichment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = False
    default_model: DefaultModel | None = None
    passes: Annotated[list[Pass] | None, Field(validate_default=True)] = []


class BulkConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding: Embedding
    chunking: Annotated[Chunking | None, Field(validate_default=True)] = {}
    enrichment: Annotated[Enrichment | None, Field(validate_default=True)] = {}
    indexing: Annotated[Indexing | None, Field(validate_default=True)] = {}
    mode: Literal["full", "embed_only", "enrichment_only"] | None = "full"
    doc_type: str | None = None
