# generated by datamodel-codegen:
#   filename:  BulkSubmitResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict


class Upload(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ordinal: int
    upload_url: AnyUrl
    upload_id: str
    expires_at: int
    method: Literal["PUT"]
    headers: dict[str, str]


class BulkSubmitResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    bulk_job_id: str
    state: str
    total_files: int
    uploads: list[Upload]
    expires_at: int
