# generated by datamodel-codegen:
#   filename:  BulkJobCounts.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class BulkJobCounts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    pending: int
    uploaded: int
    finalized: int
    enqueued: int
    processing: int
    succeeded: int
    failed: int
    skipped: int
