# generated by datamodel-codegen:
#   filename:  BulkFileEntry.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class BulkFileEntry(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ordinal: Annotated[int, Field(ge=0)]
    filename: Annotated[str, Field(max_length=512, min_length=1)]
    size_bytes: Annotated[int, Field(gt=0, le=26214400)]
    content_type: Annotated[str, Field(min_length=1)]
    client_request_id: str | None = None
