# generated by datamodel-codegen:
#   filename:  ChatRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Messages(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["system", "user", "assistant"]
    content: str


class Messages1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["developer"]
    content: str


class ResponseFormat(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["text"]


class ResponseFormat1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["json_object"]


class ResponseFormat2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["json_schema"]
    schema_: Annotated[dict[str, Any], Field(alias="schema")]
    name: str | None = None
    strict: bool | None = None


class ChatRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model: Annotated[str, Field(min_length=1)]
    messages: Annotated[list[Messages | Messages1], Field(min_length=1)]
    max_tokens: Annotated[int | None, Field(gt=0)] = None
    temperature: Annotated[float | None, Field(ge=0.0, le=2.0)] = None
    response_format: ResponseFormat | ResponseFormat1 | ResponseFormat2 | None = None
    stop: list[str] | None = None
