# generated by datamodel-codegen:
#   filename:  ChatResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str
    parsed: Any | None = None
    usage: Usage
    model: str
    finish_reason: Literal["stop", "length", "tool_use", "content_filter", "other"]
