# generated by datamodel-codegen:
#   filename:  ChatMessage.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel


class ChatMessage1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["system", "user", "assistant"]
    content: str


class ChatMessage2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["developer"]
    content: str


class ChatMessage(RootModel[ChatMessage1 | ChatMessage2]):
    root: ChatMessage1 | ChatMessage2
