# generated by datamodel-codegen:
#   filename:  ChunkingConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ChunkingConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    profile: str | None = "generic"
    target_tokens: Annotated[int | None, Field(gt=0)] = 600
    overlap_tokens: Annotated[int | None, Field(ge=0)] = 80
    boundary_depth: Annotated[int | None, Field(ge=0)] = 2
