# generated by datamodel-codegen:
#   filename:  Chunk.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class Chunk(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    namespace_id: str
    document_id: str
    version_id: str
    version_index_id: str
    artifact_type: str
    """
    Class of chunk. `passage` is the default body text; corpus profiles can introduce others (e.g., `summary`, `theme`, `character_arc`).
    """
    section_path: str | None
    ord: int
    text: str
    metadata: dict[str, Any] | None
    embedding_profile: str
    chunking_profile: str
    embedding_status: Literal["pending", "embedded", "missing"]
    embedding_dimensions: int | None
    parent_chunk_id: str | None
    enrichment_pass_id: str | None
    created_at: int
