# generated by datamodel-codegen:
#   filename:  ChunkEmbeddingStatus.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class ChunkEmbeddingStatus(RootModel[Literal["pending", "embedded", "missing"]]):
    root: Literal["pending", "embedded", "missing"]
