# generated by datamodel-codegen:
#   filename:  ChunkArtifactType.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import RootModel


class ChunkArtifactType(RootModel[str]):
    root: str
    """
    Class of chunk. `passage` is the default body text; corpus profiles can introduce others (e.g., `summary`, `theme`, `character_arc`).
    """
