# generated by datamodel-codegen:
#   filename:  Citation.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Citation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    n: Annotated[int, Field(gt=0)]
    chunk_id: str
    section_path: str | None
    quote: str | None = None
