# generated by datamodel-codegen:
#   filename:  ContextConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ContextConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_context_tokens: Annotated[int | None, Field(gt=0)] = 12000
    allow_compression: bool | None = False
