# generated by datamodel-codegen:
#   filename:  DegradationLevel.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class DegradationLevel(RootModel[Literal["full", "no_citations", "partial", "cannot_answer"]]):
    root: Literal["full", "no_citations", "partial", "cannot_answer"]
