# generated by datamodel-codegen:
#   filename:  Document.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class Document(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    namespace_id: str
    title: str | None
    doc_type: str | None
    metadata: dict[str, Any] | None
    current_version_id: str | None
    created_at: int
