# generated by datamodel-codegen:
#   filename:  DocumentCreate.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class DocumentCreate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    title: str | None = None
    doc_type: str | None = None
    metadata: dict[str, Any] | None = None
