# generated by datamodel-codegen:
#   filename:  EmbeddingResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: Annotated[int, Field(ge=0)]


class EmbeddingResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    vectors: list[list[float]]
    model: str
    usage: Usage
