# generated by datamodel-codegen:
#   filename:  EmbeddingRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class EmbeddingRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model: Annotated[str, Field(min_length=1)]
    input: Annotated[list[str], Field(min_length=1)]
