# generated by datamodel-codegen:
#   filename:  EnrichmentPass.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Model1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
    model: Annotated[str, Field(min_length=1)]
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class EnrichmentPass(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: Annotated[str, Field(min_length=1)]
    enabled: bool | None = True
    required: bool | None = False
    model: Model1 | None = None
