# generated by datamodel-codegen:
#   filename:  ErrorEnvelope.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class Error(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: Literal[
        "INTERNAL",
        "NOT_FOUND",
        "BAD_REQUEST",
        "INVALID_API_KEY",
        "TENANT_NOT_FOUND",
        "NAMESPACE_NOT_FOUND",
        "NAMESPACE_ALREADY_EXISTS",
        "NAMESPACE_DIMENSION_MISMATCH",
        "PROVIDER_KEY_NOT_FOUND",
        "PROVIDER_KEY_INVALID",
        "PROVIDER_KEY_VALIDATION_FAILED",
        "INFRA_KEY_NOT_FOUND",
        "INFRA_KEY_ALREADY_REGISTERED",
        "PROVIDER_QUOTA_EXHAUSTED",
        "PROVIDER_RATE_LIMITED",
        "PROVIDER_TIMEOUT",
        "PROVIDER_UNAVAILABLE",
        "PROVIDER_REFUSAL",
        "PROVIDER_MALFORMED_RESPONSE",
        "PROVIDER_UNSUPPORTED_MODEL",
        "CONTEXT_LENGTH_EXCEEDED",
        "DOCUMENT_NOT_FOUND",
        "DOCUMENT_VERSION_NOT_FOUND",
        "UPLOAD_VALIDATION_FAILED",
        "UPLOAD_INTENT_NOT_FOUND",
        "INDEX_ALREADY_BUILT",
        "INGESTION_IN_PROGRESS",
        "INGESTION_FAILED",
        "JOB_NOT_RUNNING",
        "JOB_CANCELLED",
        "UNSUPPORTED_CHUNK_JSONL_SCHEMA",
        "EMBEDDING_PROFILE_MISMATCH",
        "RETRIEVAL_FAILED",
        "SYNTHESIS_FAILED",
        "EMPTY_QUERY",
        "QUERY_RESPONSE_UNAVAILABLE",
        "UNKNOWN_CORPUS_PROFILE",
        "ENRICHMENT_PASS_FAILED",
        "INPUT_TOO_LARGE_FOR_PASS",
        "INTERNAL_AUTH_REQUIRED",
        "INTERNAL_TIMESTAMP_OUT_OF_WINDOW",
        "INTERNAL_SIGNATURE_INVALID",
        "INTERNAL_OWNERSHIP_MISMATCH",
        "DLQ_NOT_FOUND",
        "DLQ_NOT_DEAD_LETTERED",
        "ADMIN_RATE_LIMITED",
        "INSUFFICIENT_SCOPE",
        "STREAM_INTERRUPTED",
        "EVAL_SET_NOT_FOUND",
        "EVAL_QUESTION_NOT_FOUND",
        "EVAL_RUN_NOT_FOUND",
        "EVAL_RUN_FAILED",
        "EVAL_JUDGE_FAILED",
        "TOKEN_EXPIRED",
        "TOKEN_ALREADY_USED",
        "TENANT_REGISTRATION_DISABLED",
        "RATE_LIMITED",
        "BULK_TOO_MANY_FILES",
        "BULK_BYTES_EXCEEDED",
        "BULK_DUPLICATE_FILENAMES_IN_JOB",
        "BULK_DIMENSION_LOCK_MISMATCH",
        "BULK_NAMESPACE_NOT_FOUND",
        "BULK_PROVIDER_KEY_NOT_FOUND",
        "BULK_QUOTA_EXCEEDED",
        "BULK_DUPLICATE_REQUEST_ID_DIFFERENT_MANIFEST",
        "BULK_JOB_NOT_FOUND",
        "BULK_JOB_TERMINAL",
        "BULK_JOB_HAS_SUCCEEDED_FILES",
        "BULK_JOB_CANCELLED",
        "BULK_FILE_NOT_FOUND",
        "BULK_FILE_HASH_MISMATCH",
        "BULK_FILE_UPLOAD_EXPIRED",
        "BULK_FILE_UPLOAD_INVALID_STATE",
        "BULK_FILE_FORMAT_UNSUPPORTED",
        "BULK_FILE_PROVIDER_THROTTLED",
        "BULK_FILE_FINALIZE_FAILED",
        "BULK_FILE_INGEST_FAILED",
        "INGEST_LEASE_RECOVERY_EXHAUSTED",
        "NOT_IMPLEMENTED",
    ]
    message: str
    request_id: str | None = None
    details: dict[str, Any] | None = None


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    error: Error
