# generated by datamodel-codegen:
#   filename:  EvalRunDetail.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Result(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    question_id: str
    passed: bool
    scores: dict[Literal["relevance", "groundedness", "citation_quality"], int]
    query_event_id: str | None
    error_message: str | None


class EvalRunDetail(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    eval_set_id: str
    status: Literal["pending", "running", "completed", "failed"]
    num_questions: int
    num_passed: int
    num_failed: int
    started_at: float | None
    completed_at: float | None
    error_message: str | None
    created_at: float
    results: list[Result]
