# generated by datamodel-codegen:
#   filename:  EvalResult.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class EvalResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    question_id: str
    passed: bool
    scores: dict[Literal["relevance", "groundedness", "citation_quality"], int]
    query_event_id: str | None
    error_message: str | None
