# generated by datamodel-codegen:
#   filename:  EvalSetWithQuestions.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Question(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    question: Annotated[str, Field(max_length=2000, min_length=1)]
    expected_answer: Annotated[str | None, Field(max_length=8000)] = None
    must_cite_chunk_ids: list[str] | None = None
    judge_overrides: (
        dict[Literal["relevance", "groundedness", "citation_quality"], str] | None
    ) = None
    id: str
    created_at: float


class EvalSetWithQuestions(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    namespace_id: str
    name: Annotated[str, Field(max_length=120, min_length=1)]
    created_at: float
    questions: list[Question]
