# generated by datamodel-codegen:
#   filename:  EvalSet.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class EvalSet(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    namespace_id: str
    name: Annotated[str, Field(max_length=120, min_length=1)]
    created_at: float
