# generated by datamodel-codegen:
#   filename:  EvalRunStatus.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class EvalRunStatus(RootModel[Literal["pending", "running", "completed", "failed"]]):
    root: Literal["pending", "running", "completed", "failed"]
