# generated by datamodel-codegen:
#   filename:  FinalizeResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FinalizeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    version_id: str
    content_hash: str
    source_r2_key: str
    size_bytes: int
    content_type: str
    deduplicated: bool
