# generated by datamodel-codegen:
#   filename:  IndexedProfile.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class IndexedProfile(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    chunking_profile: str
    embedding_profile: str
    embedding_provider: str
    embedding_model: str
    embedding_dimensions: int
