# generated by datamodel-codegen:
#   filename:  IndexingConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class IndexingConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    replace_existing_vectors: bool | None = False
    artifact_types: list[str] | None = ["passage"]
