# generated by datamodel-codegen:
#   filename:  InferenceConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class InferenceConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "workers_ai", "cohere", "voyage"]
    model: Annotated[str, Field(min_length=1)]
    provider_key_ref: str | None = None
    provider_key_id: str | None = None
    max_output_tokens: Annotated[int | None, Field(gt=0)] = None
    temperature: Annotated[float | None, Field(ge=0.0, le=2.0)] = None
