# generated by datamodel-codegen:
#   filename:  InfraKeyCreate.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class InfraKeyCreate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["pinecone"]
    label: Annotated[
        str, Field(max_length=40, min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$")
    ]
    key: Annotated[str, Field(max_length=512, min_length=8)]
