# generated by datamodel-codegen:
#   filename:  InfraKeyTestResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class InfraKeyTestResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ok: bool
    error_code: str | None = None
    error_message: str | None = None
