# generated by datamodel-codegen:
#   filename:  InfraKeyLabel.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class InfraKeyLabel(RootModel[str]):
    root: Annotated[
        str, Field(max_length=40, min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$")
    ]
