# generated by datamodel-codegen:
#   filename:  IngestionOutcome.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class IngestionOutcome(RootModel[Literal["full_success", "partial_ingestion", "fatal_failure"]]):
    root: Literal["full_success", "partial_ingestion", "fatal_failure"]
