# generated by datamodel-codegen:
#   filename:  IngestionJob.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class IngestionJob(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    document_id: str
    version_id: str
    version_index_id: str
    mode: Literal["full", "embed_only", "enrichment_only"]
    status: Literal["pending", "running", "retrying", "completed", "failed"]
    current_stage: str | None
    error_code: str | None
    error_message: str | None
    attempt_count: int
    created_at: int
    completed_at: int | None
