# generated by datamodel-codegen:
#   filename:  KnownModelList.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SupportedDimension(RootModel[int]):
    root: Annotated[int, Field(gt=0)]


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Wire-format model ID, exactly as the provider expects.
    """
    provider: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
    kind: Literal["embedding", "inference", "rerank"]
    family: Literal[
        "openai_chat",
        "openai_reasoning",
        "openai_embedding",
        "anthropic_messages",
        "voyage_rerank",
        "cohere_rerank",
        "workers_ai_chat",
        "workers_ai_embedding",
    ]
    dimensions: Annotated[int | None, Field(gt=0)] = None
    supported_dimensions: list[SupportedDimension] | None = None
    tier: Literal["flagship", "standard", "mini", "lite"] | None = None
    deprecated: bool | None = None
    notes: str | None = None


class KnownModelList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    data: list[Datum]
