# generated by datamodel-codegen:
#   filename:  ListModelsQuery.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class ListModelsQuery(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: (
        Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"] | None
    ) = None
    kind: Literal["embedding", "inference", "rerank"] | None = None
    include_deprecated: bool | None = None
