# generated by datamodel-codegen:
#   filename:  ModelKind.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class ModelKind(RootModel[Literal["embedding", "inference", "rerank"]]):
    root: Literal["embedding", "inference", "rerank"]
