# generated by datamodel-codegen:
#   filename:  ModelFamily.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class ModelFamily(
    RootModel[
        Literal[
            "openai_chat",
            "openai_reasoning",
            "openai_embedding",
            "anthropic_messages",
            "voyage_rerank",
            "cohere_rerank",
            "workers_ai_chat",
            "workers_ai_embedding",
        ]
    ]
):
    root: Literal[
        "openai_chat",
        "openai_reasoning",
        "openai_embedding",
        "anthropic_messages",
        "voyage_rerank",
        "cohere_rerank",
        "workers_ai_chat",
        "workers_ai_embedding",
    ]
