# generated by datamodel-codegen:
#   filename:  NamespaceCreate.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class NamespaceCreate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    slug: Annotated[
        str, Field(max_length=31, min_length=2, pattern="^[a-z][a-z0-9-]+$")
    ]
    corpus_profile: str | None = "generic"
    default_embedding_profile: str | None = "openai-text-embedding-3-large"
    embedding_dimensions: Annotated[int | None, Field(ge=1, le=4096)] = None
    default_inference_model: str | None = None
    default_prompt_template_id: str | None = None
    vector_backend: Literal["vectorize", "qdrant", "pinecone"] | None = "vectorize"
    """
    Vector store backend, locked at create time. `vectorize` (default): Cloudflare Vectorize V2; binding is global and Textral isolates by metadata filter. `qdrant`: self-host or Qdrant Cloud; Textral creates a per-namespace collection idempotently. `pinecone`: managed Pinecone serverless; **the operator must pre-create the index** (dimensions matching `default_embedding_profile`) and pass its host URL as `vector_index_name`. See the Namespaces tag description for the full operator-config matrix.
    """
    vector_index_name: Annotated[str | None, Field(max_length=512, min_length=1)] = None
    """
    Backend-meaningful handle. Vectorize: must be omitted (binding is global). Qdrant: collection name — Textral auto-creates the collection idempotently at namespace-create time. Pinecone: full data-plane host URL of a **pre-existing** index (e.g. `https://my-idx-xxxxx.svc.us-east-1-aws.pinecone.io`); Textral verifies reachability but does not create Pinecone indexes. Provision the index via the Pinecone console / API first; dimensions must match `default_embedding_profile`. Locked at create time — switching backends requires a new namespace + re-ingest.
    """
    vector_namespace: Annotated[
        str | None, Field(max_length=63, pattern="^[a-z0-9][a-z0-9_-]*$")
    ] = None
    """
    Pinecone: the native Pinecone namespace inside the index. Multiple Textral namespaces can share one Pinecone index by using different values here. Defaults to the Textral slug if omitted. Qdrant / Vectorize: ignored. Locked at create time.
    """
