# generated by datamodel-codegen:
#   filename:  Namespace.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class IndexedProfile(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    chunking_profile: str
    embedding_profile: str
    embedding_provider: str
    embedding_model: str
    embedding_dimensions: int


class Namespace(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    slug: Annotated[
        str, Field(max_length=31, min_length=2, pattern="^[a-z][a-z0-9-]+$")
    ]
    corpus_profile: str
    default_embedding_profile: str
    embedding_dimensions: Annotated[int, Field(gt=0)]
    default_inference_model: str | None
    default_prompt_template_id: str | None
    vector_backend: Literal["vectorize", "qdrant", "pinecone"]
    """
    Vector store backend, locked at create time. `vectorize` (default): Cloudflare Vectorize V2; binding is global and Textral isolates by metadata filter. `qdrant`: self-host or Qdrant Cloud; Textral creates a per-namespace collection idempotently. `pinecone`: managed Pinecone serverless; **the operator must pre-create the index** (dimensions matching `default_embedding_profile`) and pass its host URL as `vector_index_name`. See the Namespaces tag description for the full operator-config matrix.
    """
    vector_index_name: str | None
    """
    Backend-meaningful handle. Vectorize: null (binding is global). Qdrant: collection name (Textral-managed). Pinecone: full data-plane host URL of the operator-provisioned index.
    """
    vector_namespace: str | None
    """
    Vector-store-side partition handle. Pinecone: the native Pinecone namespace inside the index — many Textral namespaces can share one Pinecone index by using different values here. Qdrant / Vectorize: null (not used).
    """
    indexed_profiles: list[IndexedProfile] | None = None
    created_at: int
