# generated by datamodel-codegen:
#   filename:  NamespaceUpdate.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class NamespaceUpdate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    corpus_profile: str | None = "generic"
    default_embedding_profile: str | None = "openai-text-embedding-3-large"
    default_inference_model: str | None = None
    default_prompt_template_id: str | None = None
