# generated by datamodel-codegen:
#   filename:  NamespaceSlug.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class NamespaceSlug(RootModel[str]):
    root: Annotated[
        str, Field(max_length=31, min_length=2, pattern="^[a-z][a-z0-9-]+$")
    ]
