# generated by datamodel-codegen:
#   filename:  OutputConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class OutputConfig1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["text"]


class OutputConfig2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["structured"]
    schema_: Annotated[dict[str, Any], Field(alias="schema")]


class OutputConfig(RootModel[OutputConfig1 | OutputConfig2]):
    root: OutputConfig1 | OutputConfig2
