# generated by datamodel-codegen:
#   filename:  PromptConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PromptConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    system: str | None = None
    developer: str | None = None
    template_id: str | None = None
