# generated by datamodel-codegen:
#   filename:  ProviderName.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class ProviderName(
    RootModel[Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]]
):
    root: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
