# generated by datamodel-codegen:
#   filename:  ProviderKey.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ProviderKey(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    provider: Literal["openai", "anthropic", "cohere", "voyage", "workers_ai"]
    label: Annotated[
        str, Field(max_length=40, min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$")
    ]
    prefix: str
    last_validated_at: float | None
    last_error_code: str | None
    created_at: float
