# generated by datamodel-codegen:
#   filename:  QueryResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Answer(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["text"]
    text: str


class Answer4(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["structured"]
    object: Any | None = None
    raw: str | None = None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    n: Annotated[int, Field(gt=0)]
    chunk_id: str
    section_path: str | None
    quote: str | None = None


class Reranker(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool
    executed: bool
    provider: str | None = None
    model: str | None = None
    top_n: int | None = None
    latency_ms: int | None = None
    fallback_reason: (
        Literal[
            "PROVIDER_UNAVAILABLE",
            "PROVIDER_QUOTA_EXHAUSTED",
            "PROVIDER_TIMEOUT",
            "PROVIDER_KEY_NOT_FOUND",
            "EMPTY_INPUT",
        ]
        | None
    ) = None
    actionable: bool | None = None
    fallback_message: str | None = None


class Tokens(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding_input: int
    synthesis_input: int
    synthesis_output: int
    context: int


class Audit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding_profile: str
    chunking_profile: str
    inference_provider: str
    inference_model: str
    provider_key_id: str | None
    retrieval_strategy: str
    retrieval_status: Literal["full", "dense_only", "sparse_only", "empty"]
    dense_candidates_returned: int
    sparse_candidates_returned: int
    dense_error: str | None = None
    sparse_error: str | None = None
    embedding_missing_count: int
    candidates_returned: int
    reranker: Reranker
    citation_integrity: Literal["valid", "invalid_removed", "missing"] | None
    synthesis_status: Literal["success", "truncated", "failed"] | None
    dropped_citations: list[int]
    tokens: Tokens
    total_cost_usd_micros: int | None
    latency_ms: int


class QueryResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    query_event_id: str
    answer: Answer | Answer4
    citations: list[Citation]
    degradation_level: Literal["full", "no_citations", "partial", "cannot_answer"]
    audit: Audit
