# generated by datamodel-codegen:
#   filename:  QueryAudit.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Reranker(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool
    executed: bool
    provider: str | None = None
    model: str | None = None
    top_n: int | None = None
    latency_ms: int | None = None
    fallback_reason: (
        Literal[
            "PROVIDER_UNAVAILABLE",
            "PROVIDER_QUOTA_EXHAUSTED",
            "PROVIDER_TIMEOUT",
            "PROVIDER_KEY_NOT_FOUND",
            "EMPTY_INPUT",
        ]
        | None
    ) = None
    actionable: bool | None = None
    fallback_message: str | None = None


class Tokens(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding_input: int
    synthesis_input: int
    synthesis_output: int
    context: int


class QueryAudit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding_profile: str
    chunking_profile: str
    inference_provider: str
    inference_model: str
    provider_key_id: str | None
    retrieval_strategy: str
    retrieval_status: Literal["full", "dense_only", "sparse_only", "empty"]
    dense_candidates_returned: int
    sparse_candidates_returned: int
    dense_error: str | None = None
    sparse_error: str | None = None
    embedding_missing_count: int
    candidates_returned: int
    reranker: Reranker
    citation_integrity: Literal["valid", "invalid_removed", "missing"] | None
    synthesis_status: Literal["success", "truncated", "failed"] | None
    dropped_citations: list[int]
    tokens: Tokens
    total_cost_usd_micros: int | None
    latency_ms: int
