# generated by datamodel-codegen:
#   filename:  QueryEvent.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class QueryEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    tenant_id: str
    namespace_id: str
    status: Literal[
        "received",
        "retrieval_started",
        "retrieval_completed",
        "synthesis_started",
        "completed",
        "failed",
    ]
    query_text: str
    request_config: dict[str, Any]
    degradation_level: (
        Literal["full", "no_citations", "partial", "cannot_answer"] | None
    )
    retrieval_status: str | None
    citation_integrity: str | None
    synthesis_status: str | None
    candidates_returned: int | None
    citations_returned: int | None
    dropped_citations: list[int] | None
    latency_ms: int | None
    answer_r2_key: str | None
    mirror_error: str | None
    error_code: str | None
    error_message: str | None
    created_at: int
    completed_at: int | None
