# generated by datamodel-codegen:
#   filename:  QueryRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Embedding(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "workers_ai", "cohere", "voyage"]
    model: Annotated[str, Field(min_length=1)]
    dimensions: Annotated[int | None, Field(gt=0)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class Inference(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Literal["openai", "anthropic", "workers_ai", "cohere", "voyage"]
    model: Annotated[str, Field(min_length=1)]
    provider_key_ref: str | None = None
    provider_key_id: str | None = None
    max_output_tokens: Annotated[int | None, Field(gt=0)] = None
    temperature: Annotated[float | None, Field(ge=0.0, le=2.0)] = None


class Chunking(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    profile: str | None = "generic"


class Rerank(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    provider: Literal["voyage", "cohere"] | None = None
    model: Annotated[str | None, Field(min_length=1)] = None
    top_n: Annotated[int | None, Field(gt=0, le=200)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class Retrieval(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    strategy: Literal["hybrid_rrf"] | None = "hybrid_rrf"
    top_k_dense: Annotated[int | None, Field(gt=0)] = 30
    top_k_sparse: Annotated[int | None, Field(gt=0)] = 30
    rrf_k: Annotated[int | None, Field(gt=0)] = 60
    artifact_types: list[str] | None = ["passage"]
    require_citations: bool | None = True
    rerank: Rerank | None = None


class Context(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_context_tokens: Annotated[int | None, Field(gt=0)] = 12000
    allow_compression: bool | None = False


class Prompt(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    system: str | None = None
    developer: str | None = None
    template_id: str | None = None


class Output(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["text"]


class Output1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["structured"]
    schema_: Annotated[dict[str, Any], Field(alias="schema")]


class QueryRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    namespace: Annotated[str, Field(min_length=1)]
    document_ids: list[str] | None = None
    query: Annotated[str, Field(min_length=1)]
    embedding: Embedding
    inference: Inference
    chunking: Annotated[Chunking | None, Field(validate_default=True)] = {}
    retrieval: Annotated[Retrieval | None, Field(validate_default=True)] = {}
    context: Annotated[Context | None, Field(validate_default=True)] = {}
    prompt: Annotated[Prompt | None, Field(validate_default=True)] = {}
    output: Annotated[Output | Output1 | None, Field(validate_default=True)] = {
        "mode": "text"
    }
