# generated by datamodel-codegen:
#   filename:  RecoverRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class RecoverRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    email: Annotated[EmailStr, Field(max_length=254)]
