# generated by datamodel-codegen:
#   filename:  RedeemNamespace.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RedeemNamespace(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    slug: str
