# generated by datamodel-codegen:
#   filename:  RedeemRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class RedeemRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    token: Annotated[str, Field(max_length=64, min_length=20)]
