# generated by datamodel-codegen:
#   filename:  RedeemResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Tenant(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    display_name: str
    owner_email: str


class Namespace(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    slug: str


class ApiKey(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    raw: str
    """
    Returned exactly once on redemption; never persisted in cleartext.
    """
    prefix: str
    scopes: list[str]


class RedeemResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tenant: Tenant
    namespace: Namespace | None = None
    api_key: ApiKey
