# generated by datamodel-codegen:
#   filename:  RedeemApiKey.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RedeemApiKey(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    raw: str
    """
    Returned exactly once on redemption; never persisted in cleartext.
    """
    prefix: str
    scopes: list[str]
