# generated by datamodel-codegen:
#   filename:  RerankerFallbackReason.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class RerankerFallbackReason(
    RootModel[
        Literal[
            "PROVIDER_UNAVAILABLE",
            "PROVIDER_QUOTA_EXHAUSTED",
            "PROVIDER_TIMEOUT",
            "PROVIDER_KEY_NOT_FOUND",
            "EMPTY_INPUT",
        ]
    ]
):
    root: Literal[
        "PROVIDER_UNAVAILABLE",
        "PROVIDER_QUOTA_EXHAUSTED",
        "PROVIDER_TIMEOUT",
        "PROVIDER_KEY_NOT_FOUND",
        "EMPTY_INPUT",
    ]
