# generated by datamodel-codegen:
#   filename:  RerankOverride.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class RerankOverride(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    provider: Literal["voyage", "cohere"] | None = None
    model: Annotated[str | None, Field(min_length=1)] = None
    top_n: Annotated[int | None, Field(gt=0, le=200)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None
