# generated by datamodel-codegen:
#   filename:  RerankResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Result(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    index: Annotated[int, Field(ge=0)]
    score: float


class RerankResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    results: list[Result]
    model: str
