# generated by datamodel-codegen:
#   filename:  RerankRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class RerankRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model: Annotated[str, Field(min_length=1)]
    query: Annotated[str, Field(min_length=1)]
    documents: Annotated[list[str], Field(min_length=1)]
    top_n: Annotated[int | None, Field(gt=0)] = None
