# generated by datamodel-codegen:
#   filename:  RerankerAudit.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class RerankerAudit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool
    executed: bool
    provider: str | None = None
    model: str | None = None
    top_n: int | None = None
    latency_ms: int | None = None
    fallback_reason: (
        Literal[
            "PROVIDER_UNAVAILABLE",
            "PROVIDER_QUOTA_EXHAUSTED",
            "PROVIDER_TIMEOUT",
            "PROVIDER_KEY_NOT_FOUND",
            "EMPTY_INPUT",
        ]
        | None
    ) = None
    actionable: bool | None = None
    fallback_message: str | None = None
