# generated by datamodel-codegen:
#   filename:  ResponseFormat.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ResponseFormat3(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["text"]


class ResponseFormat4(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["json_object"]


class ResponseFormat5(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["json_schema"]
    schema_: Annotated[dict[str, Any], Field(alias="schema")]
    name: str | None = None
    strict: bool | None = None


class ResponseFormat(RootModel[ResponseFormat3 | ResponseFormat4 | ResponseFormat5]):
    root: ResponseFormat3 | ResponseFormat4 | ResponseFormat5
