# generated by datamodel-codegen:
#   filename:  RetrievalConfig.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Rerank(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    provider: Literal["voyage", "cohere"] | None = None
    model: Annotated[str | None, Field(min_length=1)] = None
    top_n: Annotated[int | None, Field(gt=0, le=200)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class RetrievalConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    strategy: Literal["hybrid_rrf"] | None = "hybrid_rrf"
    top_k_dense: Annotated[int | None, Field(gt=0)] = 30
    top_k_sparse: Annotated[int | None, Field(gt=0)] = 30
    rrf_k: Annotated[int | None, Field(gt=0)] = 60
    artifact_types: list[str] | None = ["passage"]
    require_citations: bool | None = True
    rerank: Rerank | None = None
