# generated by datamodel-codegen:
#   filename:  StageAttempt.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class StageAttempt(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    job_id: str
    stage: str
    attempt: int
    status: Literal["started", "completed", "failed", "skipped"]
    started_at: int
    completed_at: int | None
    duration_ms: int | None
    metadata: dict[str, Any] | None
    error_code: str | None
    error_message: str | None
