# generated by datamodel-codegen:
#   filename:  StartEvalRunRequest.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Inference(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Annotated[str, Field(min_length=1)]
    model: Annotated[str, Field(min_length=1)]
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class Embedding(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    provider: Annotated[str, Field(min_length=1)]
    model: Annotated[str, Field(min_length=1)]
    dimensions: Annotated[int | None, Field(gt=0)] = None
    provider_key_ref: str | None = None
    provider_key_id: str | None = None


class StartEvalRunRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    inference: Inference
    embedding: Embedding
    pass_threshold: Annotated[int | None, Field(ge=1, le=5)] = 4
