# generated by datamodel-codegen:
#   filename:  TokenBreakdown.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TokenBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    embedding_input: int
    synthesis_input: int
    synthesis_output: int
    context: int
