# generated by datamodel-codegen:
#   filename:  UploadResponse.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict


class UploadResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    upload_id: str
    url: AnyUrl
    key: str
    expires_at: int
