# generated by datamodel-codegen:
#   filename:  UploadCreate.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class UploadCreate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content_type: Annotated[str, Field(min_length=1)]
    size_bytes: Annotated[int, Field(gt=0, le=26214400)]
