# generated by datamodel-codegen:
#   filename:  VectorBackend.json
#   timestamp: 2026-05-09T00:31:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class VectorBackend(RootModel[Literal["vectorize", "qdrant", "pinecone"]]):
    root: Literal["vectorize", "qdrant", "pinecone"]
    """
    Vector store backend, locked at create time. `vectorize` (default): Cloudflare Vectorize V2; binding is global and Textral isolates by metadata filter. `qdrant`: self-host or Qdrant Cloud; Textral creates a per-namespace collection idempotently. `pinecone`: managed Pinecone serverless; **the operator must pre-create the index** (dimensions matching `default_embedding_profile`) and pass its host URL as `vector_index_name`. See the Namespaces tag description for the full operator-config matrix.
    """
